// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Skyrise Bureau Swift Playgrounds",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Skyrise Bureau Swift Playgrounds",
            targets: ["AppModule"],
            bundleIdentifier: "com.advaitconty.ssc.Skyrise-Bureau-Swift-Playgrounds",
            teamIdentifier: "MK2VQ82S9T",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/buh/CompactSlider.git", "2.1.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CompactSlider", package: "compactslider")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.v5]
)