// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Skyrise Bureau",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Skyrise Bureau",
            targets: ["AppModule"],
            bundleIdentifier: "com.advaitconty.ssc.Skyrise-Bureau-Swift-Playgrounds",
            teamIdentifier: "MK2VQ82S9T",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .plane),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ],
            appCategory: .simulationGames
        )
    ],
    dependencies: [
        .package(url: "https://github.com/buh/CompactSlider.git", "2.1.0"..<"3.0.0"),
        .package(url: "https://github.com/maplibre/maplibre-gl-native-distribution.git", "6.22.1"..<"7.0.0"),
        .package(url: "https://github.com/maplibre/swiftui-dsl.git", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CompactSlider", package: "compactslider"),
                .product(name: "MapLibre", package: "maplibre-gl-native-distribution"),
                .product(name: "MapLibreSwiftDSL", package: "swiftui-dsl"),
                .product(name: "MapLibreSwiftMacros", package: "swiftui-dsl"),
                .product(name: "MapLibreSwiftUI", package: "swiftui-dsl")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.v5]
)