//
//  TestMapView.swift
//  Skyrise Bureau
//
//  Created by Milind Contractor on 02/01/26.
//

import SwiftUI


// Test stubs - as generated by AI
#Preview {
    @Previewable @State var position = OfflineMapPosition.world

    OfflineMap(position: $position) {
        OfflineMapContentGroup(
            annotations: [
                OfflineAnnotation(
                    id: "LHR",
                    coordinate: .init(latitude: 51.47, longitude: -0.45),
                    kind: .airport(iata: "LHR", icao: "EGLL", name: "London Heathrow", city: "London", country: "United Kingdom", isHub: true)
                ),
                OfflineAnnotation(
                    id: "BLR",
                    coordinate: .init(latitude: 13.19, longitude: 77.70),
                    kind: .airport(iata: "BLR", icao: "VOBL", name: "Kempegowda International Airport", city: "Bengaluru", country: "India", isHub: true)
                ),
                OfflineAnnotation(
                    id: "plane-1",
                    coordinate: .init(latitude: 35.0, longitude: 30.0),
                    kind: .aircraft(registration: "VT-SKR", isAirborne: true, heading: 120)
                ),
            ],
            routes: [
                OfflineRoute(
                    origin: .init(latitude: 51.47, longitude: -0.45),
                    destination: .init(latitude: 13.19, longitude: 77.70),
                    isActive: true
                )
            ]
        )
    }}
