//
//  AircraftDatabase.swift
//  Skyrise Bureau SSC
//
//  Created by Milind Contractor on 22/2/26.
//

import Foundation

// MARK: Aircraft Database
class AircraftDatabase {
    static let shared = AircraftDatabase()
    
    let allAircraft: [Aircraft]
    
    init() {
        allAircraft = [
            // EXTRAS
            Aircraft(
                modelCode: "TU144",
                name: "Tupolev Tu-144",
                manufacturer: .tupolev,
                category: .extras,
                description: "The Soviet Union's supersonic rival to the Concorde. Despite its troubled service history, the Tu-144 represents an ambitious era of aviation innovation.",
                maxRange: 6500,
                cruiseSpeed: 2150,
                maxSeats: 140,
                fuelCapacity: 70000,
                fuelBurnRate: 15.5,
                minRunwayLength: 3200,
                defaultSeating: SeatingConfig(economy: 90, premiumEconomy: 0, business: 20, first: 0),
                purchasePrice: 120_000_000,
                maintenanceCostPerHour: 25000,
                yearIntroduced: 1968,
                isEndgame: false,
                isSupersonic: true,
                customImageHeight: 250,
                pilots: 3,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "CONCORDE",
                name: "BAC-Aérospatiale Concorde",
                manufacturer: .airbus,
                category: .extras,
                description: "The iconic supersonic airliner that redefined luxury air travel. Capable of crossing the Atlantic in under 3.5 hours at twice the speed of sound.",
                maxRange: 7250,
                cruiseSpeed: 2180,
                maxSeats: 128,
                fuelCapacity: 95680,
                fuelBurnRate: 17.2,
                minRunwayLength: 3400,
                defaultSeating: SeatingConfig(economy: 0, premiumEconomy: 0, business: 64, first: 0),
                purchasePrice: 150_000_000,
                maintenanceCostPerHour: 30000,
                yearIntroduced: 1976,
                isEndgame: false,
                isSupersonic: true,
                customImageHeight: 150,
                pilots: 3,
                flightAttendents: 6
            ),
            Aircraft(
                modelCode: "DHC6",
                name: "De Havilland Canada DHC-6 'Twin Otter'",
                manufacturer: .dehavilland,
                category: .extras,
                description: "A rugged STOL aircraft perfect for remote operations. Known for its exceptional short-field performance and reliability in harsh conditions.",
                maxRange: 1300,
                cruiseSpeed: 340,
                maxSeats: 19,
                fuelCapacity: 1137,
                fuelBurnRate: 0.35,
                minRunwayLength: 335,
                defaultSeating: SeatingConfig(economy: 19, premiumEconomy: 0, business: 0, first: 0),
                purchasePrice: 6_500_000,
                maintenanceCostPerHour: 450,
                yearIntroduced: 1965,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 0
            ),
            
            // COMMUTER
            Aircraft(
                modelCode: "ATR42",
                name: "ATR 42",
                manufacturer: .atr,
                category: .commuter,
                description: "A fuel-efficient turboprop ideal for regional routes. Popular with airlines for its low operating costs and reliable performance.",
                maxRange: 1528,
                cruiseSpeed: 510,
                maxSeats: 50,
                fuelCapacity: 4500,
                fuelBurnRate: 0.65,
                minRunwayLength: 1165,
                defaultSeating: SeatingConfig(economy: 50, premiumEconomy: 0, business: 0, first: 0),
                purchasePrice: 18_000_000,
                maintenanceCostPerHour: 850,
                yearIntroduced: 1985,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 1
            ),
            Aircraft(
                modelCode: "ATR72",
                name: "ATR 72",
                manufacturer: .atr,
                category: .commuter,
                description: "The stretched version of the ATR 42, offering more capacity while maintaining excellent fuel efficiency for short-haul operations.",
                maxRange: 1528,
                cruiseSpeed: 510,
                maxSeats: 78,
                fuelCapacity: 5000,
                fuelBurnRate: 0.75,
                minRunwayLength: 1333,
                defaultSeating: SeatingConfig(economy: 72, premiumEconomy: 4, business: 0, first: 0),
                purchasePrice: 26_000_000,
                maintenanceCostPerHour: 1100,
                yearIntroduced: 1989,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "DHC8",
                name: "De Havilland Canada DHC-8 Dash 8 (Q400)",
                manufacturer: .dehavilland,
                category: .commuter,
                description: "A versatile turboprop with advanced noise reduction. The Q400 variant offers near-jet speeds with turboprop economics.",
                maxRange: 2040,
                cruiseSpeed: 667,
                maxSeats: 90,
                fuelCapacity: 6526,
                fuelBurnRate: 0.85,
                minRunwayLength: 1425,
                defaultSeating: SeatingConfig(economy: 78, premiumEconomy: 8, business: 0, first: 0),
                purchasePrice: 32_000_000,
                maintenanceCostPerHour: 1350,
                yearIntroduced: 1984,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 2
            ),
            
            // REGIONAL JETS
            Aircraft(
                modelCode: "ERJ145",
                name: "ERJ 145",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "A pioneering 50-seat regional jet that revolutionized short-haul travel. Compact and efficient for thin routes.",
                maxRange: 3334,
                cruiseSpeed: 833,
                maxSeats: 50,
                fuelCapacity: 5737,
                fuelBurnRate: 1.1,
                minRunwayLength: 1753,
                defaultSeating: SeatingConfig(economy: 46, premiumEconomy: 0, business: 2, first: 0),
                purchasePrice: 30_000_000,
                maintenanceCostPerHour: 1450,
                yearIntroduced: 1996,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "ERJ170",
                name: "ERJ 170",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "Part of Embraer's E-Jet family, offering mainline comfort in a regional package. Popular for its passenger appeal and economics.",
                maxRange: 3889,
                cruiseSpeed: 870,
                maxSeats: 80,
                fuelCapacity: 9980,
                fuelBurnRate: 1.45,
                minRunwayLength: 1644,
                defaultSeating: SeatingConfig(economy: 66, premiumEconomy: 6, business: 3, first: 0),
                purchasePrice: 45_000_000,
                maintenanceCostPerHour: 1850,
                yearIntroduced: 2004,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "ERJ190",
                name: "ERJ 190",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "The largest of the first-generation E-Jets, bridging the gap between regional and narrow-body aircraft with excellent range.",
                maxRange: 4537,
                cruiseSpeed: 870,
                maxSeats: 114,
                fuelCapacity: 13365,
                fuelBurnRate: 1.75,
                minRunwayLength: 1778,
                defaultSeating: SeatingConfig(economy: 88, premiumEconomy: 12, business: 4, first: 0),
                purchasePrice: 52_000_000,
                maintenanceCostPerHour: 2100,
                yearIntroduced: 2005,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "E175E2",
                name: "ERJ 175-E2",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "The second-generation E-Jet with improved fuel efficiency and lower emissions. Features advanced aerodynamics and modern engines.",
                maxRange: 3704,
                cruiseSpeed: 871,
                maxSeats: 90,
                fuelCapacity: 11340,
                fuelBurnRate: 1.35,
                minRunwayLength: 1644,
                defaultSeating: SeatingConfig(economy: 70, premiumEconomy: 8, business: 4, first: 0),
                purchasePrice: 56_000_000,
                maintenanceCostPerHour: 1950,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 2
            ),
            Aircraft(
                modelCode: "E190E2",
                name: "ERJ 190-E2",
                manufacturer: .embraer,
                category: .regionalJet,
                description: "The enhanced E190 with new-generation engines and winglets. Offers 17% lower fuel consumption than its predecessor.",
                maxRange: 5278,
                cruiseSpeed: 871,
                maxSeats: 114,
                fuelCapacity: 13620,
                fuelBurnRate: 1.65,
                minRunwayLength: 1704,
                defaultSeating: SeatingConfig(economy: 88, premiumEconomy: 12, business: 4, first: 0),
                purchasePrice: 62_000_000,
                maintenanceCostPerHour: 2050,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "A220-300",
                name: "Airbus A220-300",
                manufacturer: .airbus,
                category: .regionalJet,
                description: "Originally the Bombardier CSeries, this cutting-edge aircraft offers mainline comfort with regional jet efficiency and exceptional range.",
                maxRange: 6297,
                cruiseSpeed: 870,
                maxSeats: 160,
                fuelCapacity: 21945,
                fuelBurnRate: 2.15,
                minRunwayLength: 1463,
                defaultSeating: SeatingConfig(economy: 120, premiumEconomy: 18, business: 8, first: 0),
                purchasePrice: 91_000_000,
                maintenanceCostPerHour: 2650,
                yearIntroduced: 2016,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "SSJ100",
                name: "Sukhoi Superjet 100",
                manufacturer: .sukhoi,
                category: .regionalJet,
                description: "Russia's modern regional jet featuring Western avionics. Designed for efficiency on short to medium-haul routes.",
                maxRange: 4578,
                cruiseSpeed: 828,
                maxSeats: 108,
                fuelCapacity: 13790,
                fuelBurnRate: 1.8,
                minRunwayLength: 1780,
                defaultSeating: SeatingConfig(economy: 84, premiumEconomy: 10, business: 4, first: 0),
                purchasePrice: 36_000_000,
                maintenanceCostPerHour: 1750,
                yearIntroduced: 2011,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "CRJ900",
                name: "Bombardier CRJ900",
                manufacturer: .bombardier,
                category: .regionalJet,
                description: "A versatile 90-seat regional jet offering excellent range and reliability. Popular with regional carriers for its passenger comfort and operational efficiency.",
                maxRange: 3704,
                cruiseSpeed: 870,
                maxSeats: 90,
                fuelCapacity: 10705,
                fuelBurnRate: 1.6,
                minRunwayLength: 1645,
                defaultSeating: SeatingConfig(economy: 70, premiumEconomy: 10, business: 5, first: 0),
                purchasePrice: 48_000_000,
                maintenanceCostPerHour: 1900,
                yearIntroduced: 2003,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 145,
                pilots: 2,
                flightAttendents: 2
            ),
            // NARROW BODY
            Aircraft(
                modelCode: "A318",
                name: "Airbus A318",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The smallest member of the A320 family, nicknamed 'Baby Bus'. Perfect for thin routes and hot-and-high operations.",
                maxRange: 5950,
                cruiseSpeed: 829,
                maxSeats: 136,
                fuelCapacity: 24210,
                fuelBurnRate: 2.4,
                minRunwayLength: 1780,
                defaultSeating: SeatingConfig(economy: 102, premiumEconomy: 12, business: 6, first: 0),
                purchasePrice: 75_000_000,
                maintenanceCostPerHour: 2800,
                yearIntroduced: 2003,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "A319",
                name: "Airbus A319",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "A versatile narrow-body with excellent range for its size. Popular with both mainline and low-cost carriers worldwide.",
                maxRange: 6850,
                cruiseSpeed: 829,
                maxSeats: 156,
                fuelCapacity: 23859,
                fuelBurnRate: 2.55,
                minRunwayLength: 2090,
                defaultSeating: SeatingConfig(economy: 114, premiumEconomy: 16, business: 8, first: 0),
                purchasePrice: 92_000_000,
                maintenanceCostPerHour: 3100,
                yearIntroduced: 1996,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 115,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A320",
                name: "Airbus A320",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The world's best-selling single-aisle airliner. Revolutionary fly-by-wire technology and exceptional reliability made it an industry standard.",
                maxRange: 6150,
                cruiseSpeed: 829,
                maxSeats: 180,
                fuelCapacity: 27200,
                fuelBurnRate: 2.75,
                minRunwayLength: 2090,
                defaultSeating: SeatingConfig(economy: 132, premiumEconomy: 18, business: 10, first: 0),
                purchasePrice: 101_000_000,
                maintenanceCostPerHour: 3300,
                yearIntroduced: 1988,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A321",
                name: "Airbus A321",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The largest A320 family member, offering maximum capacity and flexibility. The stretched fuselage maximizes efficiency on high-density routes.",
                maxRange: 5950,
                cruiseSpeed: 829,
                maxSeats: 220,
                fuelCapacity: 32840,
                fuelBurnRate: 3.1,
                minRunwayLength: 2180,
                defaultSeating: SeatingConfig(economy: 156, premiumEconomy: 24, business: 12, first: 0),
                purchasePrice: 118_000_000,
                maintenanceCostPerHour: 3600,
                yearIntroduced: 1994,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "A319neo",
                name: "Airbus A319neo",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The new engine option A319 with improved fuel efficiency and reduced emissions. Features sharklet wingtips and modern engines.",
                maxRange: 6850,
                cruiseSpeed: 833,
                maxSeats: 160,
                fuelCapacity: 26730,
                fuelBurnRate: 2.35,
                minRunwayLength: 2000,
                defaultSeating: SeatingConfig(economy: 116, premiumEconomy: 16, business: 8, first: 0),
                purchasePrice: 102_000_000,
                maintenanceCostPerHour: 2950,
                yearIntroduced: 2019,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A320neo",
                name: "Airbus A320neo",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The next generation A320 with 15% better fuel efficiency. New engines and aerodynamic improvements maintain Airbus's narrow-body dominance.",
                maxRange: 6300,
                cruiseSpeed: 833,
                maxSeats: 194,
                fuelCapacity: 26730,
                fuelBurnRate: 2.5,
                minRunwayLength: 2000,
                defaultSeating: SeatingConfig(economy: 138, premiumEconomy: 20, business: 12, first: 0),
                purchasePrice: 110_500_000,
                maintenanceCostPerHour: 3050,
                yearIntroduced: 2016,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "A321neo",
                name: "Airbus A321neo",
                manufacturer: .airbus,
                category: .narrowBody,
                description: "The most capable single-aisle aircraft available. Exceptional range enables transatlantic routes while maintaining excellent economics.",
                maxRange: 7400,
                cruiseSpeed: 833,
                maxSeats: 244,
                fuelCapacity: 32840,
                fuelBurnRate: 2.85,
                minRunwayLength: 2180,
                defaultSeating: SeatingConfig(economy: 168, premiumEconomy: 28, business: 16, first: 0),
                purchasePrice: 129_500_000,
                maintenanceCostPerHour: 3400,
                yearIntroduced: 2016,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "DC9-31",
                name: "DC-9-31",
                manufacturer: .mcdonnellDouglas,
                category: .narrowBody,
                description: "A classic short-haul jet from aviation's golden age. The DC-9's simplicity and reliability made it a workhorse for decades.",
                maxRange: 2150,
                cruiseSpeed: 810,
                maxSeats: 115,
                fuelCapacity: 13636,
                fuelBurnRate: 2.8,
                minRunwayLength: 1920,
                defaultSeating: SeatingConfig(economy: 99, premiumEconomy: 6, business: 4, first: 0),
                purchasePrice: 45_000_000,
                maintenanceCostPerHour: 2400,
                yearIntroduced: 1967,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "MD82",
                name: "MD-82",
                manufacturer: .mcdonnellDouglas,
                category: .narrowBody,
                description: "Part of the MD-80 'Super 80' series, a stretched DC-9 variant. Known for its distinctive rear-mounted engines and long service life.",
                maxRange: 3540,
                cruiseSpeed: 811,
                maxSeats: 172,
                fuelCapacity: 21114,
                fuelBurnRate: 3.25,
                minRunwayLength: 2438,
                defaultSeating: SeatingConfig(economy: 132, premiumEconomy: 16, business: 8, first: 0),
                purchasePrice: 62_000_000,
                maintenanceCostPerHour: 3000,
                yearIntroduced: 1981,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B707-320C",
                name: "Boeing 707-320C",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The aircraft that ushered in the jet age. The 707 revolutionized long-haul travel and established Boeing as a commercial aviation leader.",
                maxRange: 9400,
                cruiseSpeed: 885,
                maxSeats: 189,
                fuelCapacity: 90770,
                fuelBurnRate: 5.2,
                minRunwayLength: 3048,
                defaultSeating: SeatingConfig(economy: 126, premiumEconomy: 24, business: 12, first: 2),
                purchasePrice: 55_000_000,
                maintenanceCostPerHour: 4200,
                yearIntroduced: 1958,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B717-200",
                name: "Boeing 717-200",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "Originally the MD-95, this efficient 100-seater excels on short-haul routes. Known for low noise and excellent hot-day performance.",
                maxRange: 3815,
                cruiseSpeed: 811,
                maxSeats: 134,
                fuelCapacity: 17560,
                fuelBurnRate: 2.5,
                minRunwayLength: 1860,
                defaultSeating: SeatingConfig(economy: 104, premiumEconomy: 12, business: 6, first: 0),
                purchasePrice: 48_000_000,
                maintenanceCostPerHour: 2300,
                yearIntroduced: 1999,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "B727-200",
                name: "Boeing 727-200",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "A tri-jet legend with exceptional short-field performance. The 727's versatility made it one of aviation's most successful airliners.",
                maxRange: 4630,
                cruiseSpeed: 917,
                maxSeats: 189,
                fuelCapacity: 31755,
                fuelBurnRate: 4.0,
                minRunwayLength: 2438,
                defaultSeating: SeatingConfig(economy: 138, premiumEconomy: 18, business: 10, first: 0),
                purchasePrice: 58_000_000,
                maintenanceCostPerHour: 3500,
                yearIntroduced: 1967,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B737-200ADV",
                name: "Boeing 737-200 Advance",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The improved second generation 737 with more powerful engines. A rugged workhorse that served in the harshest conditions worldwide.",
                maxRange: 3700,
                cruiseSpeed: 815,
                maxSeats: 136,
                fuelCapacity: 19640,
                fuelBurnRate: 2.9,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 108, premiumEconomy: 10, business: 6, first: 0),
                purchasePrice: 42_000_000,
                maintenanceCostPerHour: 2500,
                yearIntroduced: 1971,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "B737-300",
                name: "Boeing 737-300",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The first 737 Classic variant, featuring modern turbofan engines. Launched the 737 into the jet age and saved Boeing's narrow-body program.",
                maxRange: 4400,
                cruiseSpeed: 794,
                maxSeats: 149,
                fuelCapacity: 23814,
                fuelBurnRate: 2.95,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 114, premiumEconomy: 12, business: 8, first: 0),
                purchasePrice: 68_000_000,
                maintenanceCostPerHour: 2850,
                yearIntroduced: 1984,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 3
            ),
            Aircraft(
                modelCode: "B737-800NG",
                name: "Boeing 737-800 NG",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The most popular 737 variant ever built. Exceptional reliability and economics made it the backbone of countless airline fleets.",
                maxRange: 5436,
                cruiseSpeed: 842,
                maxSeats: 189,
                fuelCapacity: 26020,
                fuelBurnRate: 2.7,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 138, premiumEconomy: 18, business: 10, first: 0),
                purchasePrice: 102_000_000,
                maintenanceCostPerHour: 3150,
                yearIntroduced: 1998,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 2,
                flightAttendents: 4
            ),
            Aircraft(
                modelCode: "B737MAX8",
                name: "Boeing 737 MAX 8",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The latest generation 737 with 14% better fuel efficiency. Advanced winglets and engines provide excellent performance and range.",
                maxRange: 6570,
                cruiseSpeed: 839,
                maxSeats: 210,
                fuelCapacity: 25816,
                fuelBurnRate: 2.45,
                minRunwayLength: 2042,
                defaultSeating: SeatingConfig(economy: 150, premiumEconomy: 22, business: 12, first: 0),
                purchasePrice: 121_600_000,
                maintenanceCostPerHour: 3050,
                yearIntroduced: 2017,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "B737MAX9",
                name: "Boeing 737 MAX 9",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "The stretched MAX variant offering increased capacity. Maintains the MAX family's efficiency while serving high-density markets.",
                maxRange: 6570,
                cruiseSpeed: 839,
                maxSeats: 220,
                fuelCapacity: 25816,
                fuelBurnRate: 2.55,
                minRunwayLength: 2550,
                defaultSeating: SeatingConfig(economy: 156, premiumEconomy: 24, business: 14, first: 0),
                purchasePrice: 128_900_000,
                maintenanceCostPerHour: 3200,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "B757-200",
                name: "Boeing 757-200",
                manufacturer: .boeing,
                category: .narrowBody,
                description: "A powerful narrow-body with exceptional hot-and-high performance. The 757's range and capability made it irreplaceable on many routes.",
                maxRange: 7222,
                cruiseSpeed: 850,
                maxSeats: 239,
                fuelCapacity: 43490,
                fuelBurnRate: 3.4,
                minRunwayLength: 2072,
                defaultSeating: SeatingConfig(economy: 162, premiumEconomy: 30, business: 16, first: 0),
                purchasePrice: 125_000_000,
                maintenanceCostPerHour: 3800,
                yearIntroduced: 1983,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "TU204SM",
                name: "Tupolev Tu-204SM",
                manufacturer: .tupolev,
                category: .narrowBody,
                description: "A modernized Russian narrow-body with Western engines and avionics. Designed to compete with Boeing and Airbus offerings.",
                maxRange: 4300,
                cruiseSpeed: 850,
                maxSeats: 210,
                fuelCapacity: 36000,
                fuelBurnRate: 3.25,
                minRunwayLength: 2300,
                defaultSeating: SeatingConfig(economy: 150, premiumEconomy: 22, business: 12, first: 0),
                purchasePrice: 72_000_000,
                maintenanceCostPerHour: 3100,
                yearIntroduced: 2010,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 2,
                flightAttendents: 5
            ),
            Aircraft(
                modelCode: "MC21-300",
                name: "Irkut MC-21-300",
                manufacturer: .irkut,
                category: .narrowBody,
                description: "Russia's most advanced narrow-body jet featuring composite wings. Designed for efficiency and passenger comfort with a spacious cabin.",
                maxRange: 6000,
                cruiseSpeed: 870,
                maxSeats: 211,
                fuelCapacity: 23790,
                fuelBurnRate: 2.6,
                minRunwayLength: 2100,
                defaultSeating: SeatingConfig(economy: 150, premiumEconomy: 22, business: 12, first: 0),
                purchasePrice: 92_000_000,
                maintenanceCostPerHour: 3000,
                yearIntroduced: 2017,
                isEndgame: false,
                isSupersonic: false,
                pilots: 2,
                flightAttendents: 5
            ),
            
            // WIDE BODY
            Aircraft(
                modelCode: "A330-300",
                name: "Airbus A330-300",
                manufacturer: .airbus,
                category: .wideBody,
                description: "A versatile twin-engine wide-body perfect for long-haul routes. Excellent economics and reliability made it a favorite for international carriers.",
                maxRange: 10800,
                cruiseSpeed: 871,
                maxSeats: 440,
                fuelCapacity: 139090,
                fuelBurnRate: 5.8,
                minRunwayLength: 2770,
                defaultSeating: SeatingConfig(economy: 252, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 264_000_000,
                maintenanceCostPerHour: 8500,
                yearIntroduced: 1993,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "A330neo-900",
                name: "Airbus A330-900neo",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The enhanced A330 with new engines and improved aerodynamics. 14% lower fuel consumption extends the A330's competitive life.",
                maxRange: 13334,
                cruiseSpeed: 871,
                maxSeats: 460,
                fuelCapacity: 139090,
                fuelBurnRate: 5.2,
                minRunwayLength: 2770,
                defaultSeating: SeatingConfig(economy: 264, premiumEconomy: 54, business: 30, first: 6),
                purchasePrice: 296_400_000,
                maintenanceCostPerHour: 8200,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 15
            ),
            Aircraft(
                modelCode: "A340-300",
                name: "Airbus A340-300",
                manufacturer: .airbus,
                category: .wideBody,
                description: "A four-engine long-haul aircraft designed for ultra-long routes. The extra engines provided ETOPS-free operations over remote areas.",
                maxRange: 13500,
                cruiseSpeed: 871,
                maxSeats: 440,
                fuelCapacity: 147850,
                fuelBurnRate: 6.5,
                minRunwayLength: 2990,
                defaultSeating: SeatingConfig(economy: 252, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 275_000_000,
                maintenanceCostPerHour: 9200,
                yearIntroduced: 1993,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "A340-600",
                name: "Airbus A340-600",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The longest commercial airliner when introduced. Exceptional range and capacity made it ideal for prestige long-haul routes.",
                maxRange: 14630,
                cruiseSpeed: 871,
                maxSeats: 475,
                fuelCapacity: 204500,
                fuelBurnRate: 7.2,
                minRunwayLength: 3000,
                defaultSeating: SeatingConfig(economy: 280, premiumEconomy: 56, business: 30, first: 8),
                purchasePrice: 302_000_000,
                maintenanceCostPerHour: 10500,
                yearIntroduced: 2002,
                isEndgame: false,
                isSupersonic: false,
                pilots: 4,
                flightAttendents: 20
            ),
            Aircraft(
                modelCode: "A350-900",
                name: "Airbus A350-900",
                manufacturer: .airbus,
                category: .wideBody,
                description: "Airbus's cutting-edge wide-body featuring carbon-fiber construction. Advanced technology and efficiency redefine long-haul travel.",
                maxRange: 15000,
                cruiseSpeed: 903,
                maxSeats: 440,
                fuelCapacity: 138000,
                fuelBurnRate: 5.4,
                minRunwayLength: 2600,
                defaultSeating: SeatingConfig(economy: 252, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 317_400_000,
                maintenanceCostPerHour: 8800,
                yearIntroduced: 2015,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 4,
                flightAttendents: 18
            ),
            Aircraft(
                modelCode: "A350-1000",
                name: "Airbus A350-1000",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The largest A350 variant with exceptional range and capacity. Competes directly with the 777-300ER with better efficiency.",
                maxRange: 16100,
                cruiseSpeed: 903,
                maxSeats: 480,
                fuelCapacity: 156000,
                fuelBurnRate: 5.9,
                minRunwayLength: 2750,
                defaultSeating: SeatingConfig(economy: 276, premiumEconomy: 60, business: 32, first: 8),
                purchasePrice: 366_500_000,
                maintenanceCostPerHour: 9500,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 175,
                pilots: 4,
                flightAttendents: 20
            ),
            Aircraft(
                modelCode: "A380-800",
                name: "Airbus A380-800",
                manufacturer: .airbus,
                category: .wideBody,
                description: "The world's largest passenger airliner, an engineering marvel. Double-deck luxury and massive capacity redefined ultra-long-haul travel.",
                maxRange: 15200,
                cruiseSpeed: 903,
                maxSeats: 853,
                fuelCapacity: 323546,
                fuelBurnRate: 11.5,
                minRunwayLength: 2900,
                defaultSeating: SeatingConfig(economy: 450, premiumEconomy: 96, business: 58, first: 14),
                purchasePrice: 445_600_000,
                maintenanceCostPerHour: 18000,
                yearIntroduced: 2007,
                isEndgame: true,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 4,
                flightAttendents: 36
            ),
            Aircraft(
                modelCode: "B767-300ER",
                name: "Boeing 767-300ER",
                manufacturer: .boeing,
                category: .wideBody,
                description: "A medium wide-body perfect for transatlantic routes. The 767's efficiency and versatility made it a stalwart of international fleets.",
                maxRange: 11070,
                cruiseSpeed: 851,
                maxSeats: 351,
                fuelCapacity: 91370,
                fuelBurnRate: 4.8,
                minRunwayLength: 2590,
                defaultSeating: SeatingConfig(economy: 216, premiumEconomy: 42, business: 24, first: 4),
                purchasePrice: 217_900_000,
                maintenanceCostPerHour: 7200,
                yearIntroduced: 1988,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 12
            ),
            Aircraft(
                modelCode: "B777-300ER",
                name: "Boeing 777-300ER",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The world's most successful long-haul airliner. Exceptional range, capacity, and reliability dominate ultra-long-haul routes.",
                maxRange: 13649,
                cruiseSpeed: 892,
                maxSeats: 550,
                fuelCapacity: 181280,
                fuelBurnRate: 7.8,
                minRunwayLength: 3050,
                defaultSeating: SeatingConfig(economy: 310, premiumEconomy: 66, business: 38, first: 8),
                purchasePrice: 375_500_000,
                maintenanceCostPerHour: 11500,
                yearIntroduced: 2004,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 175,
                pilots: 3,
                flightAttendents: 17
            ),
            Aircraft(
                modelCode: "B777X-9",
                name: "Boeing 777-9X",
                manufacturer: .boeing,
                category: .wideBody,
                description: "Boeing's next-generation flagship with folding wingtips. Revolutionary engines and composite wings deliver unprecedented efficiency.",
                maxRange: 13500,
                cruiseSpeed: 892,
                maxSeats: 426,
                fuelCapacity: 197977,
                fuelBurnRate: 7.2,
                minRunwayLength: 3050,
                defaultSeating: SeatingConfig(economy: 258, premiumEconomy: 52, business: 30, first: 6),
                purchasePrice: 442_200_000,
                maintenanceCostPerHour: 12000,
                yearIntroduced: 2024,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "B787-9",
                name: "Boeing 787-9 'Dreamliner'",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The Dreamliner that revolutionized long-haul travel. Composite construction and advanced systems provide 20% better fuel efficiency.",
                maxRange: 14140,
                cruiseSpeed: 903,
                maxSeats: 420,
                fuelCapacity: 126206,
                fuelBurnRate: 5.6,
                minRunwayLength: 2800,
                defaultSeating: SeatingConfig(economy: 246, premiumEconomy: 48, business: 28, first: 6),
                purchasePrice: 292_500_000,
                maintenanceCostPerHour: 8600,
                yearIntroduced: 2014,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "B787-10",
                name: "Boeing 787-10 'Dreamliner'",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The largest Dreamliner variant optimized for high-capacity routes. Maintains 787 efficiency while maximizing passenger count.",
                maxRange: 11910,
                cruiseSpeed: 903,
                maxSeats: 440,
                fuelCapacity: 126206,
                fuelBurnRate: 5.8,
                minRunwayLength: 2800,
                defaultSeating: SeatingConfig(economy: 258, premiumEconomy: 54, business: 30, first: 6),
                purchasePrice: 325_800_000,
                maintenanceCostPerHour: 9000,
                yearIntroduced: 2018,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "B747-100",
                name: "Boeing 747-100",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The original Queen of the Skies that democratized air travel. Its distinctive hump and massive size changed aviation forever.",
                maxRange: 9800,
                cruiseSpeed: 907,
                maxSeats: 550,
                fuelCapacity: 183380,
                fuelBurnRate: 10.5,
                minRunwayLength: 3200,
                defaultSeating: SeatingConfig(economy: 324, premiumEconomy: 66, business: 36, first: 8),
                purchasePrice: 190_000_000,
                maintenanceCostPerHour: 12000,
                yearIntroduced: 1970,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 175,
                pilots: 3,
                flightAttendents: 11
            ),
            Aircraft(
                modelCode: "B747-200C",
                name: "Boeing 747-200C",
                manufacturer: .boeing,
                category: .wideBody,
                description: "An improved 747 with greater range and convertible cargo capability. The workhorse variant that proved the 747 concept worldwide.",
                maxRange: 12700,
                cruiseSpeed: 907,
                maxSeats: 500,
                fuelCapacity: 199158,
                fuelBurnRate: 10.8,
                minRunwayLength: 3190,
                defaultSeating: SeatingConfig(economy: 300, premiumEconomy: 60, business: 32, first: 6),
                purchasePrice: 210_000_000,
                maintenanceCostPerHour: 12500,
                yearIntroduced: 1971,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 15
            ),
            Aircraft(
                modelCode: "B747-400",
                name: "Boeing 747-400",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The most successful 747 variant with modern avionics and winglets. Dominated long-haul travel for two decades as the flagship of fleets.",
                maxRange: 13450,
                cruiseSpeed: 907,
                maxSeats: 660,
                fuelCapacity: 216840,
                fuelBurnRate: 11.2,
                minRunwayLength: 3090,
                defaultSeating: SeatingConfig(economy: 376, premiumEconomy: 78, business: 42, first: 10),
                purchasePrice: 266_500_000,
                maintenanceCostPerHour: 13500,
                yearIntroduced: 1989,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 125,
                pilots: 3,
                flightAttendents: 21
            ),
            Aircraft(
                modelCode: "B747-8I",
                name: "Boeing 747-8i",
                manufacturer: .boeing,
                category: .wideBody,
                description: "The final evolution of the 747, the longest passenger airliner. Advanced engines and aerodynamics keep the Queen competitive.",
                maxRange: 14815,
                cruiseSpeed: 907,
                maxSeats: 605,
                fuelCapacity: 238610,
                fuelBurnRate: 10.8,
                minRunwayLength: 3100,
                defaultSeating: SeatingConfig(economy: 346, premiumEconomy: 72, business: 40, first: 10),
                purchasePrice: 418_400_000,
                maintenanceCostPerHour: 15000,
                yearIntroduced: 2012,
                isEndgame: true,
                isSupersonic: false,
                pilots: 4,
                flightAttendents: 26
            ),
            Aircraft(
                modelCode: "DC10-30",
                name: "McDonnell Douglas DC-10-30",
                manufacturer: .mcdonnellDouglas,
                category: .wideBody,
                description: "A pioneering tri-jet wide-body for long-haul operations. The DC-10 opened new routes previously impossible for twin-engine aircraft.",
                maxRange: 10410,
                cruiseSpeed: 908,
                maxSeats: 380,
                fuelCapacity: 138710,
                fuelBurnRate: 8.2,
                minRunwayLength: 3020,
                defaultSeating: SeatingConfig(economy: 234, premiumEconomy: 48, business: 26, first: 4),
                purchasePrice: 180_000_000,
                maintenanceCostPerHour: 9500,
                yearIntroduced: 1972,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 200, pilots: 3,
                flightAttendents: 8
            ),
            Aircraft(
                modelCode: "MD11",
                name: "McDonnell Douglas MD-11",
                manufacturer: .mcdonnellDouglas,
                category: .wideBody,
                description: "The stretched, modernized DC-10 with advanced systems. Though commercially challenged, it found success as a freighter.",
                maxRange: 12670,
                cruiseSpeed: 876,
                maxSeats: 410,
                fuelCapacity: 146200,
                fuelBurnRate: 7.9,
                minRunwayLength: 2990,
                defaultSeating: SeatingConfig(economy: 246, premiumEconomy: 52, business: 28, first: 6),
                purchasePrice: 205_000_000,
                maintenanceCostPerHour: 10000,
                yearIntroduced: 1990,
                isEndgame: false,
                isSupersonic: false,
                customImageHeight: 150,
                pilots: 3,
                flightAttendents: 14
            ),
            Aircraft(
                modelCode: "IL96-400M",
                name: "Ilyushin IL-96-400M",
                manufacturer: .ilyushin,
                category: .wideBody,
                description: "Russia's modern four-engine wide-body with Western engines. Designed for long-haul international routes with Russian reliability.",
                maxRange: 10000,
                cruiseSpeed: 870,
                maxSeats: 436,
                fuelCapacity: 175000,
                fuelBurnRate: 8.5,
                minRunwayLength: 2850,
                defaultSeating: SeatingConfig(economy: 258, premiumEconomy: 54, business: 28, first: 6),
                purchasePrice: 175_000_000,
                maintenanceCostPerHour: 9200,
                yearIntroduced: 2012,
                isEndgame: false,
                isSupersonic: false,
                pilots: 3,
                flightAttendents: 9
            )
        ]
    }
    
    // Helper functions
    func aircraft(byCode code: String) -> Aircraft? {
        allAircraft.first { $0.modelCode == code }
    }
    
    func aircraft(byCategory category: AircraftCategory) -> [Aircraft] {
        allAircraft.filter { $0.category == category }
    }
    
    func aircraft(byManufacturer manufacturer: AircraftManufacturer) -> [Aircraft] {
        allAircraft.filter { $0.manufacturer == manufacturer }
    }
    
    func endgameAircraft() -> [Aircraft] {
        allAircraft.filter { $0.isEndgame }
    }
    
    func supersonicAircraft() -> [Aircraft] {
        allAircraft.filter { $0.isSupersonic }
    }
    
    func affordableAircraft(budget: Double) -> [Aircraft] {
        allAircraft.filter { $0.purchasePrice <= budget }
    }
    
    func aircraftForRoute(distance: Int, runwayLength: Int) -> [Aircraft] {
        allAircraft.filter { aircraft in
            aircraft.maxRange >= distance && aircraft.minRunwayLength <= runwayLength
        }
    }
}
