//
//  Database.swift
//  Skyrise Bureau
//
//  Created by Milind Contractor on 5/11/25.
//

import Foundation

// MARK: Airport Databae

class AirportDatabase {
    static let shared = AirportDatabase()
    
    let allAirports: [Airport]
    
    init() {
        allAirports = [
            // ASIA
            Airport(
                name: "Indira Gandhi International Airport",
                city: "Delhi",
                country: "India",
                iata: "DEL",
                icao: "VIDP",
                region: .asia,
                latitude: 28.5665,
                longitude: 77.1031,
                runwayLength: 4430,
                elevation: 237,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.1, businessTravelRatio: 0.65, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 2800, gatesAvailable: 95, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Chhatrapati Shivaji Maharaj International Airport",
                city: "Mumbai",
                country: "India",
                iata: "BOM",
                icao: "VABB",
                region: .asia,
                latitude: 19.0896,
                longitude: 72.8656,
                runwayLength: 3660,
                elevation: 11,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.5, businessTravelRatio: 0.70, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3200, gatesAvailable: 85, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Kempegowda International Airport",
                city: "Bengaluru",
                country: "India",
                iata: "BLR",
                icao: "VOBL",
                region: .asia,
                latitude: 13.1979,
                longitude: 77.7063,
                runwayLength: 4000,
                elevation: 915,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.8, businessTravelRatio: 0.75, tourismBoost: 0.50),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2500, gatesAvailable: 70, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Chennai International Airport",
                city: "Chennai",
                country: "India",
                iata: "MAA",
                icao: "VOMM",
                region: .asia,
                latitude: 12.9941,
                longitude: 80.1709,
                runwayLength: 3660,
                elevation: 16,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.0, businessTravelRatio: 0.60, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 120000, cargoCapacity: 2200, gatesAvailable: 60, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Rajiv Gandhi International Airport",
                city: "Hyderabad",
                country: "India",
                iata: "HYD",
                icao: "VOHS",
                region: .asia,
                latitude: 17.2403,
                longitude: 78.4294,
                runwayLength: 4260,
                elevation: 625,
                demand: AirportDemand(passengerDemand: 8.0, cargoDemand: 7.2, businessTravelRatio: 0.68, tourismBoost: 0.55),
                facilities: AirportFacilities(terminalCapacity: 130000, cargoCapacity: 2400, gatesAvailable: 65, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Singapore Changi Airport",
                city: "Singapore",
                country: "Singapore",
                iata: "SIN",
                icao: "WSSS",
                region: .asia,
                latitude: 1.3644,
                longitude: 103.9915,
                runwayLength: 4000,
                elevation: 7,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.5, businessTravelRatio: 0.80, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 220000, cargoCapacity: 4500, gatesAvailable: 115, slotEfficiency: 0.95)
            ),
            Airport(
                name: "Kuala Lumpur International Airport",
                city: "Kuala Lumpur",
                country: "Malaysia",
                iata: "KUL",
                icao: "WMKK",
                region: .asia,
                latitude: 2.7456,
                longitude: 101.7099,
                runwayLength: 4000,
                elevation: 21,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.0, businessTravelRatio: 0.65, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3000, gatesAvailable: 90, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Suvarnabhumi Airport",
                city: "Bangkok",
                country: "Thailand",
                iata: "BKK",
                icao: "VTBS",
                region: .asia,
                latitude: 13.6900,
                longitude: 100.7501,
                runwayLength: 4000,
                elevation: 2,
                demand: AirportDemand(passengerDemand: 9.3, cargoDemand: 8.3, businessTravelRatio: 0.55, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 190000, cargoCapacity: 3500, gatesAvailable: 100, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Shanghai Pudong International Airport",
                city: "Shanghai",
                country: "China",
                iata: "PVG",
                icao: "ZSPD",
                region: .asia,
                latitude: 31.1443,
                longitude: 121.8083,
                runwayLength: 4000,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.7, cargoDemand: 9.8, businessTravelRatio: 0.72, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 200000, cargoCapacity: 5000, gatesAvailable: 110, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Incheon International Airport",
                city: "Seoul",
                country: "South Korea",
                iata: "ICN",
                icao: "RKSI",
                region: .asia,
                latitude: 37.4602,
                longitude: 126.4407,
                runwayLength: 3750,
                elevation: 7,
                demand: AirportDemand(passengerDemand: 9.5, cargoDemand: 9.2, businessTravelRatio: 0.75, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 195000, cargoCapacity: 4200, gatesAvailable: 105, slotEfficiency: 0.93)
            ),
            Airport(
                name: "Narita International Airport",
                city: "Tokyo",
                country: "Japan",
                iata: "NRT",
                icao: "RJAA",
                region: .asia,
                latitude: 35.7647,
                longitude: 140.3864,
                runwayLength: 4000,
                elevation: 43,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 9.0, businessTravelRatio: 0.70, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 4000, gatesAvailable: 95, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Tokyo Haneda Airport",
                city: "Tokyo",
                country: "Japan",
                iata: "HND",
                icao: "RJTT",
                region: .asia,
                latitude: 35.5494,
                longitude: 139.7798,
                runwayLength: 3000,
                elevation: 11,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 7.5, businessTravelRatio: 0.82, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 210000, cargoCapacity: 2800, gatesAvailable: 100, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Dubai International Airport",
                city: "Dubai",
                country: "United Arab Emirates",
                iata: "DXB",
                icao: "OMDB",
                region: .asia,
                latitude: 25.2532,
                longitude: 55.3657,
                runwayLength: 4000,
                elevation: 19,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.0, businessTravelRatio: 0.78, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 230000, cargoCapacity: 4800, gatesAvailable: 120, slotEfficiency: 0.94)
            ),
            Airport(
                name: "Hamad International Airport",
                city: "Doha",
                country: "Qatar",
                iata: "DOH",
                icao: "OTHH",
                region: .asia,
                latitude: 25.2731,
                longitude: 51.6080,
                runwayLength: 4850,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.7, businessTravelRatio: 0.76, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3800, gatesAvailable: 95, slotEfficiency: 0.92)
            ),
            Airport(
                name: "King Khalid International Airport",
                city: "Riyadh",
                country: "Saudi Arabia",
                iata: "RUH",
                icao: "OERK",
                region: .asia,
                latitude: 24.9576,
                longitude: 46.6988,
                runwayLength: 4205,
                elevation: 612,
                demand: AirportDemand(passengerDemand: 8.3, cargoDemand: 7.5, businessTravelRatio: 0.72, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 150000, cargoCapacity: 2900, gatesAvailable: 80, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Muscat International Airport",
                city: "Muscat",
                country: "Oman",
                iata: "MCT",
                icao: "OOMS",
                region: .asia,
                latitude: 23.5933,
                longitude: 58.2844,
                runwayLength: 4000,
                elevation: 15,
                demand: AirportDemand(passengerDemand: 7.0, cargoDemand: 6.5, businessTravelRatio: 0.60, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 2000, gatesAvailable: 55, slotEfficiency: 0.83)
            ),
            Airport(
                name: "Hong Kong International Airport",
                city: "Hong Kong",
                country: "Hong Kong",
                iata: "HKG",
                icao: "VHHH",
                region: .asia,
                latitude: 22.3089,
                longitude: 113.9144,
                runwayLength: 3800,
                elevation: 9,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 9.9, businessTravelRatio: 0.78, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 210000, cargoCapacity: 5500, gatesAvailable: 90, slotEfficiency: 0.94)
            ),
            Airport(
                name: "Beijing Capital International Airport",
                city: "Beijing",
                country: "China",
                iata: "PEK",
                icao: "ZBAA",
                region: .asia,
                latitude: 40.0801,
                longitude: 116.5845,
                runwayLength: 3800,
                elevation: 35,
                demand: AirportDemand(passengerDemand: 9.9, cargoDemand: 9.2, businessTravelRatio: 0.75, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 220000, cargoCapacity: 4500, gatesAvailable: 120, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Guangzhou Baiyun International Airport",
                city: "Guangzhou",
                country: "China",
                iata: "CAN",
                icao: "ZGGG",
                region: .asia,
                latitude: 23.3924,
                longitude: 113.2988,
                runwayLength: 3800,
                elevation: 15,
                demand: AirportDemand(passengerDemand: 9.6, cargoDemand: 9.0, businessTravelRatio: 0.70, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 200000, cargoCapacity: 4000, gatesAvailable: 110, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Taiwan Taoyuan International Airport",
                city: "Taipei",
                country: "Taiwan",
                iata: "TPE",
                icao: "RCTP",
                region: .asia,
                latitude: 25.0777,
                longitude: 121.2328,
                runwayLength: 3660,
                elevation: 33,
                demand: AirportDemand(passengerDemand: 9.1, cargoDemand: 8.8, businessTravelRatio: 0.72, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3500, gatesAvailable: 88, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Soekarno-Hatta International Airport",
                city: "Jakarta",
                country: "Indonesia",
                iata: "CGK",
                icao: "WIII",
                region: .asia,
                latitude: -6.1256,
                longitude: 106.6559,
                runwayLength: 3660,
                elevation: 10,
                demand: AirportDemand(passengerDemand: 9.4, cargoDemand: 8.5, businessTravelRatio: 0.68, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 190000, cargoCapacity: 3800, gatesAvailable: 95, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Ninoy Aquino International Airport",
                city: "Manila",
                country: "Philippines",
                iata: "MNL",
                icao: "RPLL",
                region: .asia,
                latitude: 14.5086,
                longitude: 121.0194,
                runwayLength: 3737,
                elevation: 23,
                demand: AirportDemand(passengerDemand: 8.9, cargoDemand: 8.2, businessTravelRatio: 0.65, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3200, gatesAvailable: 80, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Abu Dhabi International Airport",
                city: "Abu Dhabi",
                country: "United Arab Emirates",
                iata: "AUH",
                icao: "OMAA",
                region: .asia,
                latitude: 24.4330,
                longitude: 54.6511,
                runwayLength: 4100,
                elevation: 27,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.5, businessTravelRatio: 0.75, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3600, gatesAvailable: 85, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Ngurah Rai International Airport",
                city: "Denpasar",
                country: "Indonesia",
                iata: "DPS",
                icao: "WADD",
                region: .asia,
                latitude: -8.7482,
                longitude: 115.1672,
                runwayLength: 3000,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 6.0, businessTravelRatio: 0.40, tourismBoost: 0.98),
                facilities: AirportFacilities(terminalCapacity: 150000, cargoCapacity: 2000, gatesAvailable: 70, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Phuket International Airport",
                city: "Phuket",
                country: "Thailand",
                iata: "HKT",
                icao: "VTSP",
                region: .asia,
                latitude: 8.1132,
                longitude: 98.3169,
                runwayLength: 3000,
                elevation: 25,
                demand: AirportDemand(passengerDemand: 8.2, cargoDemand: 5.5, businessTravelRatio: 0.38, tourismBoost: 0.97),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 1800, gatesAvailable: 65, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Tan Son Nhat International Airport",
                city: "Ho Chi Minh City",
                country: "Vietnam",
                iata: "SGN",
                icao: "VVTS",
                region: .asia,
                latitude: 10.8188,
                longitude: 106.6518,
                runwayLength: 3800,
                elevation: 10,
                demand: AirportDemand(passengerDemand: 8.7, cargoDemand: 8.0, businessTravelRatio: 0.66, tourismBoost: 0.79),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3000, gatesAvailable: 75, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Noi Bai International Airport",
                city: "Hanoi",
                country: "Vietnam",
                iata: "HAN",
                icao: "VVNB",
                region: .asia,
                latitude: 21.2212,
                longitude: 105.8072,
                runwayLength: 3800,
                elevation: 12,
                demand: AirportDemand(passengerDemand: 8.4, cargoDemand: 7.8, businessTravelRatio: 0.68, tourismBoost: 0.76),
                facilities: AirportFacilities(terminalCapacity: 150000, cargoCapacity: 2800, gatesAvailable: 70, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Kansai International Airport",
                city: "Osaka",
                country: "Japan",
                iata: "KIX",
                icao: "RJBB",
                region: .asia,
                latitude: 34.4347,
                longitude: 135.2442,
                runwayLength: 4000,
                elevation: 8,
                demand: AirportDemand(passengerDemand: 8.6, cargoDemand: 8.4, businessTravelRatio: 0.69, tourismBoost: 0.81),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 3300, gatesAvailable: 80, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Chengdu Shuangliu International Airport",
                city: "Chengdu",
                country: "China",
                iata: "CTU",
                icao: "ZUUU",
                region: .asia,
                latitude: 30.5785,
                longitude: 103.9471,
                runwayLength: 3600,
                elevation: 495,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.1, businessTravelRatio: 0.67, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3100, gatesAvailable: 85, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Shenzhen Bao'an International Airport",
                city: "Shenzhen",
                country: "China",
                iata: "SZX",
                icao: "ZGSZ",
                region: .asia,
                latitude: 22.6393,
                longitude: 113.8106,
                runwayLength: 3800,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.9, businessTravelRatio: 0.76, tourismBoost: 0.68),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3700, gatesAvailable: 90, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Xi'an Xianyang International Airport",
                city: "Xi'an",
                country: "China",
                iata: "XIY",
                icao: "ZLXY",
                region: .asia,
                latitude: 34.4471,
                longitude: 108.7515,
                runwayLength: 3800,
                elevation: 479,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.7, businessTravelRatio: 0.62, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 155000, cargoCapacity: 2900, gatesAvailable: 75, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Bandaranaike International Airport",
                city: "Colombo",
                country: "Sri Lanka",
                iata: "CMB",
                icao: "VCBI",
                region: .asia,
                latitude: 7.1809,
                longitude: 79.8853,
                runwayLength: 3350,
                elevation: 8,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 7.0, businessTravelRatio: 0.55, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 120000, cargoCapacity: 2200, gatesAvailable: 60, slotEfficiency: 0.84)
            ),
            Airport(
                name: "Al Maktoum International Airport",
                city: "Dubai",
                country: "United Arab Emirates",
                iata: "DWC",
                icao: "OMDW",
                region: .asia,
                latitude: 24.8963,
                longitude: 55.1752,
                runwayLength: 4500,
                elevation: 52,
                demand: AirportDemand(passengerDemand: 7.0, cargoDemand: 9.5, businessTravelRatio: 0.70, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 100000, cargoCapacity: 6000, gatesAvailable: 50, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Yangon International Airport",
                city: "Yangon",
                country: "Myanmar",
                iata: "RGN",
                icao: "VYYY",
                region: .asia,
                latitude: 16.9073,
                longitude: 96.1332,
                runwayLength: 3414,
                elevation: 33,
                demand: AirportDemand(passengerDemand: 7.2, cargoDemand: 6.8, businessTravelRatio: 0.50, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 2000, gatesAvailable: 50, slotEfficiency: 0.80)
            ),
            
            // EUROPE
            Airport(
                name: "Vienna International Airport",
                city: "Vienna",
                country: "Austria",
                iata: "VIE",
                icao: "LOWW",
                region: .europe,
                latitude: 48.1103,
                longitude: 16.5697,
                runwayLength: 3500,
                elevation: 183,
                demand: AirportDemand(passengerDemand: 8.0, cargoDemand: 7.2, businessTravelRatio: 0.68, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2600, gatesAvailable: 70, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Lublin Airport",
                city: "Lublin",
                country: "Poland",
                iata: "LUZ",
                icao: "EPLB",
                region: .europe,
                latitude: 51.142500,
                longitude: 22.4249,
                runwayLength: 2520,
                elevation: 193,
                demand: AirportDemand(passengerDemand: 9.9, cargoDemand: 9.9, businessTravelRatio: 0.99, tourismBoost: 0.99),
                facilities: AirportFacilities(terminalCapacity: 20000, cargoCapacity: 1000, gatesAvailable: 4, slotEfficiency: 0.75)),
            Airport(
                name: "Riga International Airport",
                city: "Riga",
                country: "Latvia",
                iata: "RIX",
                icao: "EVRA",
                region: .europe,
                latitude: 56.9236,
                longitude: 23.9711,
                runwayLength: 3200,
                elevation: 10,
                demand: AirportDemand(passengerDemand: 6.5, cargoDemand: 5.8, businessTravelRatio: 0.55, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 90000, cargoCapacity: 1800, gatesAvailable: 45, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Leonardo da Vinci-Fiumicino Airport",
                city: "Rome",
                country: "Italy",
                iata: "FCO",
                icao: "LIRF",
                region: .europe,
                latitude: 41.8003,
                longitude: 12.2389,
                runwayLength: 3900,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 7.5, businessTravelRatio: 0.62, tourismBoost: 0.92),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 2800, gatesAvailable: 85, slotEfficiency: 0.87)
            ),
            Airport(
                name: "London Heathrow Airport",
                city: "London",
                country: "United Kingdom",
                iata: "LHR",
                icao: "EGLL",
                region: .europe,
                latitude: 51.4700,
                longitude: -0.4543,
                runwayLength: 3902,
                elevation: 25,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 8.8, businessTravelRatio: 0.80, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 225000, cargoCapacity: 3800, gatesAvailable: 115, slotEfficiency: 0.93)
            ),
            Airport(
                name: "Adolfo Suárez Madrid-Barajas Airport",
                city: "Madrid",
                country: "Spain",
                iata: "MAD",
                icao: "LEMD",
                region: .europe,
                latitude: 40.4719,
                longitude: -3.5626,
                runwayLength: 4179,
                elevation: 610,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 7.8, businessTravelRatio: 0.65, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 3000, gatesAvailable: 90, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Charles de Gaulle Airport",
                city: "Paris",
                country: "France",
                iata: "CDG",
                icao: "LFPG",
                region: .europe,
                latitude: 49.0097,
                longitude: 2.5479,
                runwayLength: 4200,
                elevation: 119,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 9.0, businessTravelRatio: 0.75, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 210000, cargoCapacity: 4200, gatesAvailable: 110, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Frankfurt Airport",
                city: "Frankfurt",
                country: "Germany",
                iata: "FRA",
                icao: "EDDF",
                region: .europe,
                latitude: 50.0379,
                longitude: 8.5622,
                runwayLength: 4000,
                elevation: 111,
                demand: AirportDemand(passengerDemand: 9.7, cargoDemand: 9.5, businessTravelRatio: 0.82, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 205000, cargoCapacity: 5000, gatesAvailable: 108, slotEfficiency: 0.94)
            ),
            Airport(
                name: "Munich Airport",
                city: "Munich",
                country: "Germany",
                iata: "MUC",
                icao: "EDDM",
                region: .europe,
                latitude: 48.3537,
                longitude: 11.7750,
                runwayLength: 4000,
                elevation: 453,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.2, businessTravelRatio: 0.75, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3500, gatesAvailable: 95, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Václav Havel Airport Prague",
                city: "Prague",
                country: "Czech Republic",
                iata: "PRG",
                icao: "LKPR",
                region: .europe,
                latitude: 50.1008,
                longitude: 14.2600,
                runwayLength: 3715,
                elevation: 380,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 6.5, businessTravelRatio: 0.58, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 130000, cargoCapacity: 2200, gatesAvailable: 65, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Francisco Sá Carneiro Airport",
                city: "Porto",
                country: "Portugal",
                iata: "OPO",
                icao: "LPPR",
                region: .europe,
                latitude: 41.2481,
                longitude: -8.6814,
                runwayLength: 3480,
                elevation: 69,
                demand: AirportDemand(passengerDemand: 7.0, cargoDemand: 6.0, businessTravelRatio: 0.52, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 115000, cargoCapacity: 1900, gatesAvailable: 55, slotEfficiency: 0.84)
            ),
            Airport(
                name: "Zagreb Airport",
                city: "Zagreb",
                country: "Croatia",
                iata: "ZAG",
                icao: "LDZA",
                region: .europe,
                latitude: 45.7429,
                longitude: 16.0688,
                runwayLength: 3252,
                elevation: 108,
                demand: AirportDemand(passengerDemand: 6.2, cargoDemand: 5.5, businessTravelRatio: 0.50, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 85000, cargoCapacity: 1600, gatesAvailable: 40, slotEfficiency: 0.81)
            ),
            Airport(
                name: "Budapest Ferenc Liszt International Airport",
                city: "Budapest",
                country: "Hungary",
                iata: "BUD",
                icao: "LHBP",
                region: .europe,
                latitude: 47.4298,
                longitude: 19.2611,
                runwayLength: 3707,
                elevation: 151,
                demand: AirportDemand(passengerDemand: 7.3, cargoDemand: 6.8, businessTravelRatio: 0.60, tourismBoost: 0.83),
                facilities: AirportFacilities(terminalCapacity: 125000, cargoCapacity: 2100, gatesAvailable: 60, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Warsaw Chopin Airport",
                city: "Warsaw",
                country: "Poland",
                iata: "WAW",
                icao: "EPWA",
                region: .europe,
                latitude: 52.1657,
                longitude: 20.9671,
                runwayLength: 3690,
                elevation: 110,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.0, businessTravelRatio: 0.65, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2400, gatesAvailable: 70, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Amsterdam Airport Schiphol",
                city: "Amsterdam",
                country: "Netherlands",
                iata: "AMS",
                icao: "EHAM",
                region: .europe,
                latitude: 52.3086,
                longitude: 4.7639,
                runwayLength: 3800,
                elevation: -3,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 9.4, businessTravelRatio: 0.78, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 215000, cargoCapacity: 4800, gatesAvailable: 112, slotEfficiency: 0.93)
            ),
            Airport(
                name: "Eindhoven Airport",
                city: "Eindhoven",
                country: "Netherlands",
                iata: "EIN",
                icao: "EHEH",
                region: .europe,
                latitude: 51.45000,
                longitude: 5.37444,
                runwayLength: 3000,
                elevation: 23,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 3.2, businessTravelRatio: 0.18, tourismBoost: 0.40),
                facilities: AirportFacilities(terminalCapacity: 6_800_000, cargoCapacity: 8_000, gatesAvailable: 30, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Brussels Airport",
                city: "Brussels",
                country: "Belgium",
                iata: "BRU",
                icao: "EBBR",
                region: .europe,
                latitude: 50.9014,
                longitude: 4.4844,
                runwayLength: 3638,
                elevation: 56,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 8.8, businessTravelRatio: 0.79, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3500, gatesAvailable: 80, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Zurich Airport",
                city: "Zurich",
                country: "Switzerland",
                iata: "ZRH",
                icao: "LSZH",
                region: .europe,
                latitude: 47.4582,
                longitude: 8.5492,
                runwayLength: 3700,
                elevation: 432,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.5, businessTravelRatio: 0.85, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3800, gatesAvailable: 90, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Copenhagen Airport",
                city: "Copenhagen",
                country: "Denmark",
                iata: "CPH",
                icao: "EKCH",
                region: .europe,
                latitude: 55.6180,
                longitude: 12.6560,
                runwayLength: 3600,
                elevation: 5,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.0, businessTravelRatio: 0.72, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3000, gatesAvailable: 85, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Stockholm Arlanda Airport",
                city: "Stockholm",
                country: "Sweden",
                iata: "ARN",
                icao: "ESSA",
                region: .europe,
                latitude: 59.6498,
                longitude: 17.9238,
                runwayLength: 3301,
                elevation: 42,
                demand: AirportDemand(passengerDemand: 8.4, cargoDemand: 7.5, businessTravelRatio: 0.70, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 155000, cargoCapacity: 2800, gatesAvailable: 75, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Oslo Gardermoen Airport",
                city: "Oslo",
                country: "Norway",
                iata: "OSL",
                icao: "ENGM",
                region: .europe,
                latitude: 60.1976,
                longitude: 11.1004,
                runwayLength: 3600,
                elevation: 208,
                demand: AirportDemand(passengerDemand: 8.3, cargoDemand: 7.2, businessTravelRatio: 0.68, tourismBoost: 0.79),
                facilities: AirportFacilities(terminalCapacity: 150000, cargoCapacity: 2600, gatesAvailable: 70, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Helsinki-Vantaa Airport",
                city: "Helsinki",
                country: "Finland",
                iata: "HEL",
                icao: "EFHK",
                region: .europe,
                latitude: 60.3172,
                longitude: 24.9633,
                runwayLength: 3440,
                elevation: 55,
                demand: AirportDemand(passengerDemand: 8.2, cargoDemand: 7.8, businessTravelRatio: 0.71, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 145000, cargoCapacity: 2900, gatesAvailable: 68, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Dublin Airport",
                city: "Dublin",
                country: "Ireland",
                iata: "DUB",
                icao: "EIDW",
                region: .europe,
                latitude: 53.4264,
                longitude: -6.2499,
                runwayLength: 3110,
                elevation: 74,
                demand: AirportDemand(passengerDemand: 8.7, cargoDemand: 7.5, businessTravelRatio: 0.65, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 2800, gatesAvailable: 82, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Manchester Airport",
                city: "Manchester",
                country: "United Kingdom",
                iata: "MAN",
                icao: "EGCC",
                region: .europe,
                latitude: 53.3537,
                longitude: -2.2749,
                runwayLength: 3048,
                elevation: 78,
                demand: AirportDemand(passengerDemand: 8.6, cargoDemand: 7.0, businessTravelRatio: 0.68, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 2500, gatesAvailable: 78, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Barcelona-El Prat Airport",
                city: "Barcelona",
                country: "Spain",
                iata: "BCN",
                icao: "LEBL",
                region: .europe,
                latitude: 41.2974,
                longitude: 2.0833,
                runwayLength: 3352,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.1, cargoDemand: 7.2, businessTravelRatio: 0.60, tourismBoost: 0.94),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 2700, gatesAvailable: 90, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Lisbon Airport",
                city: "Lisbon",
                country: "Portugal",
                iata: "LIS",
                icao: "LPPT",
                region: .europe,
                latitude: 38.7742,
                longitude: -9.1342,
                runwayLength: 3805,
                elevation: 114,
                demand: AirportDemand(passengerDemand: 8.9, cargoDemand: 7.4, businessTravelRatio: 0.62, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 2900, gatesAvailable: 88, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Athens International Airport",
                city: "Athens",
                country: "Greece",
                iata: "ATH",
                icao: "LGAV",
                region: .europe,
                latitude: 37.9364,
                longitude: 23.9444,
                runwayLength: 4000,
                elevation: 94,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 6.8, businessTravelRatio: 0.55, tourismBoost: 0.92),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 2400, gatesAvailable: 80, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Istanbul Airport",
                city: "Istanbul",
                country: "Turkey",
                iata: "IST",
                icao: "LTFM",
                region: .europe,
                latitude: 41.2753,
                longitude: 28.7519,
                runwayLength: 4100,
                elevation: 99,
                demand: AirportDemand(passengerDemand: 9.6, cargoDemand: 9.1, businessTravelRatio: 0.70, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 200000, cargoCapacity: 4500, gatesAvailable: 105, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Sheremetyevo International Airport",
                city: "Moscow",
                country: "Russia",
                iata: "SVO",
                icao: "UUEE",
                region: .europe,
                latitude: 55.9726,
                longitude: 37.4146,
                runwayLength: 3700,
                elevation: 190,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.5, businessTravelRatio: 0.75, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3800, gatesAvailable: 90, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Domodedovo International Airport",
                city: "Moscow",
                country: "Russia",
                iata: "DME",
                icao: "UUDD",
                region: .europe,
                latitude: 55.4088,
                longitude: 37.9063,
                runwayLength: 3794,
                elevation: 179,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.2, businessTravelRatio: 0.72, tourismBoost: 0.62),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3500, gatesAvailable: 85, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Zakhaev International Airport",
                city: "Moscow",
                country: "Russia",
                iata: "ZIA",
                icao: "UUWZ",
                region: .europe,
                latitude: 55.9726,
                longitude: 37.4146,
                runwayLength: 4000,
                elevation: 192,
                demand: AirportDemand(passengerDemand: 9.5, cargoDemand: 8.5, businessTravelRatio: 0.70, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 190000, cargoCapacity: 4000, gatesAvailable: 100, slotEfficiency: 0.90)
            ),
            
            // AFRICA
            Airport(
                name: "Félix-Houphouët-Boigny International Airport",
                city: "Abidjan",
                country: "Ivory Coast",
                iata: "ABJ",
                icao: "DIAP",
                region: .africa,
                latitude: 5.2539,
                longitude: -3.9263,
                runwayLength: 3000,
                elevation: 7,
                demand: AirportDemand(passengerDemand: 6.0, cargoDemand: 5.5, businessTravelRatio: 0.55, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 80000, cargoCapacity: 1700, gatesAvailable: 35, slotEfficiency: 0.75)
            ),
            Airport(
                name: "Cape Town International Airport",
                city: "Cape Town",
                country: "South Africa",
                iata: "CPT",
                icao: "FACT",
                region: .africa,
                latitude: -33.9648,
                longitude: 18.6017,
                runwayLength: 3201,
                elevation: 46,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 6.8, businessTravelRatio: 0.58, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 135000, cargoCapacity: 2300, gatesAvailable: 65, slotEfficiency: 0.84)
            ),
            Airport(
                name: "O. R. Tambo International Airport",
                city: "Johannesburg",
                country: "South Africa",
                iata: "JNB",
                icao: "FAOR",
                region: .africa,
                latitude: -26.13920,
                longitude: 28.24600,
                runwayLength: 4421,
                elevation: 1694,
                demand: AirportDemand(passengerDemand: 9.4, cargoDemand: 9.0, businessTravelRatio: 0.72, tourismBoost: 0.55),
                facilities: AirportFacilities(terminalCapacity: 28_000_000, cargoCapacity: 50_000, gatesAvailable: 110, slotEfficiency: 0.92)
            ),
            Airport(
                name: "N'djili International Airport",
                city: "Kinshasa",
                country: "Democratic Republic of Congo",
                iata: "FIH",
                icao: "FZAA",
                region: .africa,
                latitude: -4.3857,
                longitude: 15.4446,
                runwayLength: 4700,
                elevation: 309,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 5.0, businessTravelRatio: 0.48, tourismBoost: 0.45),
                facilities: AirportFacilities(terminalCapacity: 70000, cargoCapacity: 1500, gatesAvailable: 30, slotEfficiency: 0.72)
            ),
            Airport(
                name: "Julius Nyerere International Airport",
                city: "Dar es Salaam",
                country: "Tanzania",
                iata: "DAR",
                icao: "HTDA",
                region: .africa,
                latitude: -6.8781,
                longitude: 39.2026,
                runwayLength: 3000,
                elevation: 17,
                demand: AirportDemand(passengerDemand: 6.5, cargoDemand: 6.0, businessTravelRatio: 0.52, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 95000, cargoCapacity: 1900, gatesAvailable: 42, slotEfficiency: 0.78)
            ),
            Airport(
                name: "Jomo Kenyatta International Airport",
                city: "Nairobi",
                country: "Kenya",
                iata: "NBO",
                icao: "HKJK",
                region: .africa,
                latitude: -1.3192,
                longitude: 36.9278,
                runwayLength: 4117,
                elevation: 1625,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 7.2, businessTravelRatio: 0.62, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 125000, cargoCapacity: 2500, gatesAvailable: 58, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Murtala Muhammed International Airport",
                city: "Lagos",
                country: "Nigeria",
                iata: "LOS",
                icao: "DNMM",
                region: .africa,
                latitude: 6.5774,
                longitude: 3.3212,
                runwayLength: 3900,
                elevation: 42,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.0, businessTravelRatio: 0.65, tourismBoost: 0.58),
                facilities: AirportFacilities(terminalCapacity: 130000, cargoCapacity: 2300, gatesAvailable: 60, slotEfficiency: 0.79)
            ),
            Airport(
                name: "Houari Boumediene Airport",
                city: "Algiers",
                country: "Algeria",
                iata: "ALG",
                icao: "DAAG",
                region: .africa,
                latitude: 36.6910,
                longitude: 3.2154,
                runwayLength: 3500,
                elevation: 25,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 6.2, businessTravelRatio: 0.58, tourismBoost: 0.68),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 2000, gatesAvailable: 50, slotEfficiency: 0.80)
            ),
            Airport(
                name: "Marrakesh Menara Airport",
                city: "Marrakesh",
                country: "Morocco",
                iata: "RAK",
                icao: "GMMX",
                region: .africa,
                latitude: 31.6069,
                longitude: -8.0363,
                runwayLength: 3100,
                elevation: 466,
                demand: AirportDemand(passengerDemand: 7.2, cargoDemand: 5.5, businessTravelRatio: 0.42, tourismBoost: 0.95),
                facilities: AirportFacilities(terminalCapacity: 115000, cargoCapacity: 1600, gatesAvailable: 48, slotEfficiency: 0.83)
            ),
            Airport(
                name: "Cairo International Airport",
                city: "Cairo",
                country: "Egypt",
                iata: "CAI",
                icao: "HECA",
                region: .africa,
                latitude: 30.1219,
                longitude: 31.4056,
                runwayLength: 4000,
                elevation: 116,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.5, businessTravelRatio: 0.60, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 155000, cargoCapacity: 2700, gatesAvailable: 75, slotEfficiency: 0.85)
            ),
            
            // NORTH AMERICA
            Airport(
                name: "Los Angeles International Airport",
                city: "Los Angeles",
                country: "United States",
                iata: "LAX",
                icao: "KLAX",
                region: .northAmerica,
                latitude: 33.9416,
                longitude: -118.4085,
                runwayLength: 3939,
                elevation: 38,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.0, businessTravelRatio: 0.72, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 240000, cargoCapacity: 4500, gatesAvailable: 130, slotEfficiency: 0.92)
            ),
            Airport(
                name: "San Francisco International Airport",
                city: "San Francisco",
                country: "United States",
                iata: "SFO",
                icao: "KSFO",
                region: .northAmerica,
                latitude: 37.6213,
                longitude: -122.3790,
                runwayLength: 3618,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.5, cargoDemand: 8.5, businessTravelRatio: 0.78, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 200000, cargoCapacity: 4000, gatesAvailable: 115, slotEfficiency: 0.91)
            ),
            Airport(
                name: "John F. Kennedy International Airport",
                city: "New York",
                country: "United States",
                iata: "JFK",
                icao: "KJFK",
                region: .northAmerica,
                latitude: 40.6413,
                longitude: -73.7781,
                runwayLength: 4423,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 10.0, cargoDemand: 9.5, businessTravelRatio: 0.82, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 250000, cargoCapacity: 5200, gatesAvailable: 128, slotEfficiency: 0.93)
            ),
            Airport(
                name: "Newark Liberty International Airport",
                city: "Newark",
                country: "United States",
                iata: "EWR",
                icao: "KEWR",
                region: .northAmerica,
                latitude: 40.6895,
                longitude: -74.1745,
                runwayLength: 3353,
                elevation: 5,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.8, businessTravelRatio: 0.80, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 185000, cargoCapacity: 3800, gatesAvailable: 102, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Tampa International Airport",
                city: "Tampa",
                country: "United States",
                iata: "TPA",
                icao: "KTPA",
                region: .northAmerica,
                latitude: 27.9755,
                longitude: -82.5332,
                runwayLength: 3353,
                elevation: 8,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 6.5, businessTravelRatio: 0.58, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 135000, cargoCapacity: 2200, gatesAvailable: 68, slotEfficiency: 0.87)
            ),
            Airport(
                name: "O'Hare International Airport",
                city: "Chicago",
                country: "United States",
                iata: "ORD",
                icao: "KORD",
                region: .northAmerica,
                latitude: 41.9742,
                longitude: -87.9073,
                runwayLength: 3962,
                elevation: 205,
                demand: AirportDemand(passengerDemand: 9.8, cargoDemand: 9.2, businessTravelRatio: 0.78, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 230000, cargoCapacity: 4800, gatesAvailable: 185, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Ottawa Macdonald-Cartier International Airport",
                city: "Ottawa",
                country: "Canada",
                iata: "YOW",
                icao: "CYOW",
                region: .northAmerica,
                latitude: 45.3225,
                longitude: -75.6692,
                runwayLength: 3048,
                elevation: 114,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 6.0, businessTravelRatio: 0.68, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 2000, gatesAvailable: 52, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Toronto Pearson International Airport",
                city: "Toronto",
                country: "Canada",
                iata: "YYZ",
                icao: "CYYZ",
                region: .northAmerica,
                latitude: 43.6777,
                longitude: -79.6248,
                runwayLength: 3389,
                elevation: 173,
                demand: AirportDemand(passengerDemand: 9.3, cargoDemand: 8.5, businessTravelRatio: 0.75, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 195000, cargoCapacity: 3800, gatesAvailable: 105, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Calgary International Airport",
                city: "Calgary",
                country: "Canada",
                iata: "YYC",
                icao: "CYYC",
                region: .northAmerica,
                latitude: 51.1139,
                longitude: -114.0203,
                runwayLength: 3658,
                elevation: 1076,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 7.0, businessTravelRatio: 0.70, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2600, gatesAvailable: 65, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Harry Reid International Airport",
                city: "Las Vegas",
                country: "United States",
                iata: "LAS",
                icao: "KLAS",
                region: .northAmerica,
                latitude: 36.0840,
                longitude: -115.1537,
                runwayLength: 4423,
                elevation: 664,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 7.2, businessTravelRatio: 0.52, tourismBoost: 0.98),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 2800, gatesAvailable: 95, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Monterey Regional Airport",
                city: "Monterey",
                country: "United States",
                iata: "MRY",
                icao: "KMRY",
                region: .northAmerica,
                latitude: 36.5870,
                longitude: -121.8430,
                runwayLength: 2348,
                elevation: 78,
                demand: AirportDemand(passengerDemand: 4.5, cargoDemand: 3.5, businessTravelRatio: 0.45, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 50000, cargoCapacity: 800, gatesAvailable: 18, slotEfficiency: 0.78)
            ),
            Airport(
                name: "Mexico City International Airport",
                city: "Mexico City",
                country: "Mexico",
                iata: "MEX",
                icao: "MMMX",
                region: .northAmerica,
                latitude: 19.4363,
                longitude: -99.0721,
                runwayLength: 3900,
                elevation: 2230,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.0, businessTravelRatio: 0.68, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3500, gatesAvailable: 85, slotEfficiency: 0.86)
            ),
            Airport(
                name: "José Martí International Airport",
                city: "Havana",
                country: "Cuba",
                iata: "HAV",
                icao: "MUHA",
                region: .northAmerica,
                latitude: 22.9892,
                longitude: -82.4091,
                runwayLength: 4000,
                elevation: 64,
                demand: AirportDemand(passengerDemand: 6.0, cargoDemand: 4.5, businessTravelRatio: 0.38, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 90000, cargoCapacity: 1400, gatesAvailable: 38, slotEfficiency: 0.75)
            ),
            
            // SOUTH AMERICA
            Airport(
                name: "Tocumen International Airport",
                city: "Panama City",
                country: "Panama",
                iata: "PTY",
                icao: "MPTO",
                region: .southAmerica,
                latitude: 9.0714,
                longitude: -79.3835,
                runwayLength: 3050,
                elevation: 27,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.5, businessTravelRatio: 0.62, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 145000, cargoCapacity: 2800, gatesAvailable: 68, slotEfficiency: 0.86)
            ),
            Airport(
                name: "El Dorado International Airport",
                city: "Bogotá",
                country: "Colombia",
                iata: "BOG",
                icao: "SKBO",
                region: .southAmerica,
                latitude: 4.7016,
                longitude: -74.1469,
                runwayLength: 3800,
                elevation: 2548,
                demand: AirportDemand(passengerDemand: 8.2, cargoDemand: 7.8, businessTravelRatio: 0.65, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3200, gatesAvailable: 75, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Simón Bolívar International Airport",
                city: "Caracas",
                country: "Venezuela",
                iata: "CCS",
                icao: "SVMI",
                region: .southAmerica,
                latitude: 10.6013,
                longitude: -66.9905,
                runwayLength: 3500,
                elevation: 72,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 5.0, businessTravelRatio: 0.52, tourismBoost: 0.58),
                facilities: AirportFacilities(terminalCapacity: 85000, cargoCapacity: 1600, gatesAvailable: 40, slotEfficiency: 0.72)
            ),
            Airport(
                name: "Jorge Chávez International Airport",
                city: "Lima",
                country: "Peru",
                iata: "LIM",
                icao: "SPJC",
                region: .southAmerica,
                latitude: -12.0219,
                longitude: -77.1143,
                runwayLength: 3507,
                elevation: 34,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.2, businessTravelRatio: 0.60, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 145000, cargoCapacity: 2700, gatesAvailable: 70, slotEfficiency: 0.85)
            ),
            Airport(
                name: "El Alto International Airport",
                city: "La Paz",
                country: "Bolivia",
                iata: "LPB",
                icao: "SLLP",
                region: .southAmerica,
                latitude: -16.5133,
                longitude: -68.1923,
                runwayLength: 4000,
                elevation: 4061,
                demand: AirportDemand(passengerDemand: 5.8, cargoDemand: 5.2, businessTravelRatio: 0.55, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 85000, cargoCapacity: 1700, gatesAvailable: 38, slotEfficiency: 0.78)
            ),
            Airport(
                name: "Arturo Merino Benítez International Airport",
                city: "Santiago",
                country: "Chile",
                iata: "SCL",
                icao: "SCEL",
                region: .southAmerica,
                latitude: -33.3930,
                longitude: -70.7858,
                runwayLength: 3800,
                elevation: 474,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.8, businessTravelRatio: 0.68, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 3000, gatesAvailable: 80, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Ministro Pistarini International Airport",
                city: "Buenos Aires",
                country: "Argentina",
                iata: "EZE",
                icao: "SAEZ",
                region: .southAmerica,
                latitude: -34.8222,
                longitude: -58.5358,
                runwayLength: 3300,
                elevation: 20,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.0, businessTravelRatio: 0.70, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3300, gatesAvailable: 85, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Brasília International Airport",
                city: "Brasília",
                country: "Brazil",
                iata: "BSB",
                icao: "SBBR",
                region: .southAmerica,
                latitude: -15.8697,
                longitude: -47.9208,
                runwayLength: 3200,
                elevation: 1061,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 7.0, businessTravelRatio: 0.72, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2500, gatesAvailable: 65, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Rio de Janeiro-Galeão International Airport",
                city: "Rio de Janeiro",
                country: "Brazil",
                iata: "GIG",
                icao: "SBGL",
                region: .southAmerica,
                latitude: -22.8099,
                longitude: -43.2505,
                runwayLength: 4000,
                elevation: 9,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.5, businessTravelRatio: 0.60, tourismBoost: 0.92),
                facilities: AirportFacilities(terminalCapacity: 165000, cargoCapacity: 2900, gatesAvailable: 78, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Carrasco International Airport",
                city: "Montevideo",
                country: "Uruguay",
                iata: "MVD",
                icao: "SUMU",
                region: .southAmerica,
                latitude: -34.8384,
                longitude: -56.0308,
                runwayLength: 2720,
                elevation: 34,
                demand: AirportDemand(passengerDemand: 6.2, cargoDemand: 5.5, businessTravelRatio: 0.58, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 95000, cargoCapacity: 1800, gatesAvailable: 42, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Silvio Pettirossi International Airport",
                city: "Asunción",
                country: "Paraguay",
                iata: "ASU",
                icao: "SGAS",
                region: .southAmerica,
                latitude: -25.2395,
                longitude: -57.5196,
                runwayLength: 3353,
                elevation: 94,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 5.0, businessTravelRatio: 0.55, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 80000, cargoCapacity: 1600, gatesAvailable: 35, slotEfficiency: 0.79)
            ),
            
            // AUSTRALIA & OCEANIA
            Airport(
                name: "Sydney Kingsford Smith Airport",
                city: "Sydney",
                country: "Australia",
                iata: "SYD",
                icao: "YSSY",
                region: .australiaAndOceania,
                latitude: -33.9461,
                longitude: 151.1772,
                runwayLength: 3962,
                elevation: 6,
                demand: AirportDemand(passengerDemand: 9.5, cargoDemand: 8.8, businessTravelRatio: 0.75, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 200000, cargoCapacity: 4000, gatesAvailable: 100, slotEfficiency: 0.92)
            ),
            Airport(
                name: "Melbourne Airport",
                city: "Melbourne",
                country: "Australia",
                iata: "MEL",
                icao: "YMML",
                region: .australiaAndOceania,
                latitude: -37.6733,
                longitude: 144.8433,
                runwayLength: 3657,
                elevation: 132,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 8.5, businessTravelRatio: 0.72, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 185000, cargoCapacity: 3800, gatesAvailable: 95, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Brisbane Airport",
                city: "Brisbane",
                country: "Australia",
                iata: "BNE",
                icao: "YBBN",
                region: .australiaAndOceania,
                latitude: -27.3842,
                longitude: 153.1175,
                runwayLength: 3500,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.0, businessTravelRatio: 0.68, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3200, gatesAvailable: 85, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Perth Airport",
                city: "Perth",
                country: "Australia",
                iata: "PER",
                icao: "YPPH",
                region: .australiaAndOceania,
                latitude: -31.9403,
                longitude: 115.9669,
                runwayLength: 3444,
                elevation: 20,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.8, businessTravelRatio: 0.70, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3000, gatesAvailable: 80, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Adelaide Airport",
                city: "Adelaide",
                country: "Australia",
                iata: "ADL",
                icao: "YPAD",
                region: .australiaAndOceania,
                latitude: -34.9450,
                longitude: 138.5306,
                runwayLength: 3100,
                elevation: 6,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.0, businessTravelRatio: 0.65, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2500, gatesAvailable: 70, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Cairns Airport",
                city: "Cairns",
                country: "Australia",
                iata: "CNS",
                icao: "YBCS",
                region: .australiaAndOceania,
                latitude: -16.8858,
                longitude: 145.7553,
                runwayLength: 3196,
                elevation: 3,
                demand: AirportDemand(passengerDemand: 7.2, cargoDemand: 5.5, businessTravelRatio: 0.45, tourismBoost: 0.95),
                facilities: AirportFacilities(terminalCapacity: 110000, cargoCapacity: 1800, gatesAvailable: 50, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Gold Coast Airport",
                city: "Gold Coast",
                country: "Australia",
                iata: "OOL",
                icao: "YBCG",
                region: .australiaAndOceania,
                latitude: -28.1644,
                longitude: 153.5047,
                runwayLength: 2492,
                elevation: 6,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 5.0, businessTravelRatio: 0.40, tourismBoost: 0.96),
                facilities: AirportFacilities(terminalCapacity: 120000, cargoCapacity: 1500, gatesAvailable: 55, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Auckland Airport",
                city: "Auckland",
                country: "New Zealand",
                iata: "AKL",
                icao: "NZAA",
                region: .australiaAndOceania,
                latitude: -37.0082,
                longitude: 174.7917,
                runwayLength: 3635,
                elevation: 7,
                demand: AirportDemand(passengerDemand: 8.9, cargoDemand: 8.2, businessTravelRatio: 0.70, tourismBoost: 0.92),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3500, gatesAvailable: 88, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Christchurch Airport",
                city: "Christchurch",
                country: "New Zealand",
                iata: "CHC",
                icao: "NZCH",
                region: .australiaAndOceania,
                latitude: -43.4894,
                longitude: 172.5322,
                runwayLength: 3288,
                elevation: 37,
                demand: AirportDemand(passengerDemand: 7.7, cargoDemand: 7.1, businessTravelRatio: 0.62, tourismBoost: 0.89),
                facilities: AirportFacilities(terminalCapacity: 135000, cargoCapacity: 2600, gatesAvailable: 65, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Wellington Airport",
                city: "Wellington",
                country: "New Zealand",
                iata: "WLG",
                icao: "NZWN",
                region: .australiaAndOceania,
                latitude: -41.3272,
                longitude: 174.8053,
                runwayLength: 2081,
                elevation: 13,
                demand: AirportDemand(passengerDemand: 7.4, cargoDemand: 6.5, businessTravelRatio: 0.68, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 125000, cargoCapacity: 2200, gatesAvailable: 60, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Nadi International Airport",
                city: "Nadi",
                country: "Fiji",
                iata: "NAN",
                icao: "NFFN",
                region: .australiaAndOceania,
                latitude: -17.7554,
                longitude: 177.4434,
                runwayLength: 3270,
                elevation: 18,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 5.2, businessTravelRatio: 0.42, tourismBoost: 0.98),
                facilities: AirportFacilities(terminalCapacity: 100000, cargoCapacity: 1600, gatesAvailable: 45, slotEfficiency: 0.83)
            ),
            Airport(
                name: "Faa'a International Airport",
                city: "Papeete",
                country: "French Polynesia",
                iata: "PPT",
                icao: "NTAA",
                region: .australiaAndOceania,
                latitude: -17.5569,
                longitude: -149.6111,
                runwayLength: 3420,
                elevation: 2,
                demand: AirportDemand(passengerDemand: 6.5, cargoDemand: 4.8, businessTravelRatio: 0.38, tourismBoost: 0.99),
                facilities: AirportFacilities(terminalCapacity: 90000, cargoCapacity: 1400, gatesAvailable: 40, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Jacksons International Airport",
                city: "Port Moresby",
                country: "Papua New Guinea",
                iata: "POM",
                icao: "AYPY",
                region: .australiaAndOceania,
                latitude: -9.4433,
                longitude: 147.2200,
                runwayLength: 2750,
                elevation: 38,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 5.8, businessTravelRatio: 0.55, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 75000, cargoCapacity: 1700, gatesAvailable: 32, slotEfficiency: 0.78)
            ),
            Airport(
                name: "La Tontouta International Airport",
                city: "Nouméa",
                country: "New Caledonia",
                iata: "NOU",
                icao: "NWWW",
                region: .australiaAndOceania,
                latitude: -22.0146,
                longitude: 166.2126,
                runwayLength: 3250,
                elevation: 16,
                demand: AirportDemand(passengerDemand: 5.2, cargoDemand: 4.5, businessTravelRatio: 0.48, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 65000, cargoCapacity: 1300, gatesAvailable: 28, slotEfficiency: 0.79)
            ),
            Airport(
                name: "Honiara International Airport",
                city: "Honiara",
                country: "Solomon Islands",
                iata: "HIR",
                icao: "AGGH",
                region: .australiaAndOceania,
                latitude: -9.4281,
                longitude: 160.0544,
                runwayLength: 2200,
                elevation: 9,
                demand: AirportDemand(passengerDemand: 4.8, cargoDemand: 4.2, businessTravelRatio: 0.50, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 50000, cargoCapacity: 1000, gatesAvailable: 20, slotEfficiency: 0.76)
            ),
            Airport(
                name: "Rarotonga International Airport",
                city: "Avarua",
                country: "Cook Islands",
                iata: "RAR",
                icao: "NCRG",
                region: .australiaAndOceania,
                latitude: -21.2027,
                longitude: -159.8056,
                runwayLength: 2328,
                elevation: 6,
                demand: AirportDemand(passengerDemand: 5.0, cargoDemand: 3.8, businessTravelRatio: 0.35, tourismBoost: 0.97),
                facilities: AirportFacilities(terminalCapacity: 60000, cargoCapacity: 900, gatesAvailable: 25, slotEfficiency: 0.80)
            ),
            Airport(
                name: "Antonio B. Won Pat International Airport",
                city: "Hagåtña",
                country: "Guam",
                iata: "GUM",
                icao: "PGUM",
                region: .australiaAndOceania,
                latitude: 13.4834,
                longitude: 144.7960,
                runwayLength: 3660,
                elevation: 91,
                demand: AirportDemand(passengerDemand: 6.2, cargoDemand: 5.5, businessTravelRatio: 0.52, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 85000, cargoCapacity: 1600, gatesAvailable: 35, slotEfficiency: 0.81)
            ),
            Airport(
                name: "Saipan International Airport",
                city: "Saipan",
                country: "Northern Mariana Islands",
                iata: "SPN",
                icao: "PGSN",
                region: .australiaAndOceania,
                latitude: 15.1190,
                longitude: 145.7290,
                runwayLength: 2652,
                elevation: 65,
                demand: AirportDemand(passengerDemand: 5.3, cargoDemand: 4.6, businessTravelRatio: 0.45, tourismBoost: 0.86),
                facilities: AirportFacilities(terminalCapacity: 70000, cargoCapacity: 1200, gatesAvailable: 30, slotEfficiency: 0.79)
            ),
            Airport(
                name: "Faleolo International Airport",
                city: "Apia",
                country: "Samoa",
                iata: "APW",
                icao: "NSFA",
                region: .australiaAndOceania,
                latitude: -13.8299,
                longitude: -171.9992,
                runwayLength: 3000,
                elevation: 18,
                demand: AirportDemand(passengerDemand: 4.5, cargoDemand: 3.5, businessTravelRatio: 0.40, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 55000, cargoCapacity: 800, gatesAvailable: 22, slotEfficiency: 0.77)
            ),
            Airport(
                name: "Fua'amotu International Airport",
                city: "Nuku'alofa",
                country: "Tonga",
                iata: "TBU",
                icao: "NFTF",
                region: .australiaAndOceania,
                latitude: -21.2412,
                longitude: -175.1496,
                runwayLength: 2681,
                elevation: 38,
                demand: AirportDemand(passengerDemand: 4.2, cargoDemand: 3.2, businessTravelRatio: 0.38, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 50000, cargoCapacity: 700, gatesAvailable: 20, slotEfficiency: 0.75)
            ),
            // RUSSIAN AIRPORTS (add to Asia section)
            Airport(
                name: "Domodedovo International Airport",
                city: "Moscow",
                country: "Russia",
                iata: "DME",
                icao: "UUDD",
                region: .asia,
                latitude: 55.4088,
                longitude: 37.9063,
                runwayLength: 3800,
                elevation: 179,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.0, businessTravelRatio: 0.70, tourismBoost: 0.68),
                facilities: AirportFacilities(terminalCapacity: 180000, cargoCapacity: 3400, gatesAvailable: 92, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Vnukovo International Airport",
                city: "Moscow",
                country: "Russia",
                iata: "VKO",
                icao: "UUWW",
                region: .asia,
                latitude: 55.5914,
                longitude: 37.2615,
                runwayLength: 3060,
                elevation: 204,
                demand: AirportDemand(passengerDemand: 8.2, cargoDemand: 7.5, businessTravelRatio: 0.68, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3000, gatesAvailable: 78, slotEfficiency: 0.86)
            ),
            Airport(
                name: "Pulkovo Airport",
                city: "Saint Petersburg",
                country: "Russia",
                iata: "LED",
                icao: "ULLI",
                region: .asia,
                latitude: 59.8003,
                longitude: 30.2625,
                runwayLength: 3780,
                elevation: 24,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 7.8, businessTravelRatio: 0.65, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3200, gatesAvailable: 82, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Koltsovo International Airport",
                city: "Yekaterinburg",
                country: "Russia",
                iata: "SVX",
                icao: "USSS",
                region: .asia,
                latitude: 56.7431,
                longitude: 60.8027,
                runwayLength: 3025,
                elevation: 237,
                demand: AirportDemand(passengerDemand: 7.0, cargoDemand: 6.5, businessTravelRatio: 0.62, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 120000, cargoCapacity: 2400, gatesAvailable: 58, slotEfficiency: 0.83)
            ),
            Airport(
                name: "Tolmachevo Airport",
                city: "Novosibirsk",
                country: "Russia",
                iata: "OVB",
                icao: "UNNT",
                region: .asia,
                latitude: 55.0126,
                longitude: 82.6507,
                runwayLength: 3600,
                elevation: 111,
                demand: AirportDemand(passengerDemand: 7.2, cargoDemand: 6.8, businessTravelRatio: 0.60, tourismBoost: 0.58),
                facilities: AirportFacilities(terminalCapacity: 125000, cargoCapacity: 2500, gatesAvailable: 60, slotEfficiency: 0.84)
            ),
            Airport(
                name: "Sochi International Airport",
                city: "Sochi",
                country: "Russia",
                iata: "AER",
                icao: "URSS",
                region: .asia,
                latitude: 43.4499,
                longitude: 39.9566,
                runwayLength: 3503,
                elevation: 28,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 5.8, businessTravelRatio: 0.45, tourismBoost: 0.90),
                facilities: AirportFacilities(terminalCapacity: 140000, cargoCapacity: 2000, gatesAvailable: 65, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Vladivostok International Airport",
                city: "Vladivostok",
                country: "Russia",
                iata: "VVO",
                icao: "UHWW",
                region: .asia,
                latitude: 43.3990,
                longitude: 132.1483,
                runwayLength: 3500,
                elevation: 14,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 6.5, businessTravelRatio: 0.58, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 115000, cargoCapacity: 2400, gatesAvailable: 52, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Krasnoyarsk International Airport",
                city: "Krasnoyarsk",
                country: "Russia",
                iata: "KJA",
                icao: "UNKL",
                region: .asia,
                latitude: 56.1729,
                longitude: 92.4933,
                runwayLength: 3400,
                elevation: 287,
                demand: AirportDemand(passengerDemand: 6.2, cargoDemand: 5.8, businessTravelRatio: 0.60, tourismBoost: 0.55),
                facilities: AirportFacilities(terminalCapacity: 100000, cargoCapacity: 2100, gatesAvailable: 45, slotEfficiency: 0.81)
            ),
            Airport(
                name: "Irkutsk International Airport",
                city: "Irkutsk",
                country: "Russia",
                iata: "IKT",
                icao: "UIII",
                region: .asia,
                latitude: 52.2680,
                longitude: 104.3889,
                runwayLength: 3000,
                elevation: 507,
                demand: AirportDemand(passengerDemand: 6.0, cargoDemand: 5.5, businessTravelRatio: 0.55, tourismBoost: 0.68),
                facilities: AirportFacilities(terminalCapacity: 95000, cargoCapacity: 2000, gatesAvailable: 42, slotEfficiency: 0.80)
            ),
            Airport(
                name: "Kazan International Airport",
                city: "Kazan",
                country: "Russia",
                iata: "KZN",
                icao: "UWKD",
                region: .asia,
                latitude: 55.6062,
                longitude: 49.2787,
                runwayLength: 3750,
                elevation: 126,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 6.2, businessTravelRatio: 0.62, tourismBoost: 0.65),
                facilities: AirportFacilities(terminalCapacity: 115000, cargoCapacity: 2300, gatesAvailable: 52, slotEfficiency: 0.83)
            ),
            Airport(
                name: "Khabarovsk Novy Airport",
                city: "Khabarovsk",
                country: "Russia",
                iata: "KHV",
                icao: "UHHH",
                region: .asia,
                latitude: 48.5280,
                longitude: 135.1884,
                runwayLength: 3500,
                elevation: 74,
                demand: AirportDemand(passengerDemand: 5.8, cargoDemand: 5.5, businessTravelRatio: 0.58, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 90000, cargoCapacity: 2000, gatesAvailable: 40, slotEfficiency: 0.80)
            ),
            Airport(
                name: "Yakutsk Airport",
                city: "Yakutsk",
                country: "Russia",
                iata: "YKS",
                icao: "UEEE",
                region: .asia,
                latitude: 62.0933,
                longitude: 129.7711,
                runwayLength: 3300,
                elevation: 100,
                demand: AirportDemand(passengerDemand: 5.2, cargoDemand: 5.0, businessTravelRatio: 0.62, tourismBoost: 0.48),
                facilities: AirportFacilities(terminalCapacity: 80000, cargoCapacity: 1800, gatesAvailable: 35, slotEfficiency: 0.78)
            ),
            
            // ALASKA & HAWAII (add to North America section)
            Airport(
                name: "Ted Stevens Anchorage International Airport",
                city: "Anchorage",
                country: "United States",
                iata: "ANC",
                icao: "PANC",
                region: .northAmerica,
                latitude: 61.1744,
                longitude: -149.9962,
                runwayLength: 3536,
                elevation: 46,
                demand: AirportDemand(passengerDemand: 7.0, cargoDemand: 9.5, businessTravelRatio: 0.60, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 125000, cargoCapacity: 5500, gatesAvailable: 58, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Fairbanks International Airport",
                city: "Fairbanks",
                country: "United States",
                iata: "FAI",
                icao: "PAFA",
                region: .northAmerica,
                latitude: 64.8151,
                longitude: -147.8561,
                runwayLength: 3048,
                elevation: 134,
                demand: AirportDemand(passengerDemand: 5.2, cargoDemand: 6.5, businessTravelRatio: 0.58, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 75000, cargoCapacity: 2800, gatesAvailable: 32, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Juneau International Airport",
                city: "Juneau",
                country: "United States",
                iata: "JNU",
                icao: "PAJN",
                region: .northAmerica,
                latitude: 58.3550,
                longitude: -134.5764,
                runwayLength: 2743,
                elevation: 6,
                demand: AirportDemand(passengerDemand: 4.8, cargoDemand: 4.5, businessTravelRatio: 0.52, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 65000, cargoCapacity: 1600, gatesAvailable: 28, slotEfficiency: 0.80)
            ),
            Airport(
                name: "Daniel K. Inouye International Airport",
                city: "Honolulu",
                country: "United States",
                iata: "HNL",
                icao: "PHNL",
                region: .northAmerica,
                latitude: 21.3187,
                longitude: -157.9225,
                runwayLength: 3749,
                elevation: 4,
                demand: AirportDemand(passengerDemand: 9.2, cargoDemand: 7.8, businessTravelRatio: 0.52, tourismBoost: 0.95),
                facilities: AirportFacilities(terminalCapacity: 190000, cargoCapacity: 3400, gatesAvailable: 98, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Kahului Airport",
                city: "Maui",
                country: "United States",
                iata: "OGG",
                icao: "PHOG",
                region: .northAmerica,
                latitude: 20.8986,
                longitude: -156.4306,
                runwayLength: 2134,
                elevation: 16,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 5.5, businessTravelRatio: 0.35, tourismBoost: 0.98),
                facilities: AirportFacilities(terminalCapacity: 135000, cargoCapacity: 1900, gatesAvailable: 58, slotEfficiency: 0.85)
            ),
            Airport(
                name: "Ellison Onizuka Kona International Airport",
                city: "Kona",
                country: "United States",
                iata: "KOA",
                icao: "PHKO",
                region: .northAmerica,
                latitude: 19.7388,
                longitude: -156.0456,
                runwayLength: 3353,
                elevation: 14,
                demand: AirportDemand(passengerDemand: 6.8, cargoDemand: 4.8, businessTravelRatio: 0.32, tourismBoost: 0.96),
                facilities: AirportFacilities(terminalCapacity: 115000, cargoCapacity: 1600, gatesAvailable: 48, slotEfficiency: 0.84)
            ),
            Airport(
                name: "Lihue Airport",
                city: "Kauai",
                country: "United States",
                iata: "LIH",
                icao: "PHLI",
                region: .northAmerica,
                latitude: 21.9760,
                longitude: -159.3390,
                runwayLength: 2012,
                elevation: 46,
                demand: AirportDemand(passengerDemand: 6.2, cargoDemand: 4.2, businessTravelRatio: 0.30, tourismBoost: 0.95),
                facilities: AirportFacilities(terminalCapacity: 95000, cargoCapacity: 1400, gatesAvailable: 42, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Hilo International Airport",
                city: "Hilo",
                country: "United States",
                iata: "ITO",
                icao: "PHTO",
                region: .northAmerica,
                latitude: 19.7214,
                longitude: -155.0480,
                runwayLength: 2987,
                elevation: 11,
                demand: AirportDemand(passengerDemand: 5.5, cargoDemand: 4.5, businessTravelRatio: 0.35, tourismBoost: 0.88),
                facilities: AirportFacilities(terminalCapacity: 80000, cargoCapacity: 1500, gatesAvailable: 35, slotEfficiency: 0.81)
            ),
            
            // ADDITIONAL NORTH AMERICAN (add to North America section)
            Airport(
                name: "Philadelphia International Airport",
                city: "Philadelphia",
                country: "United States",
                iata: "PHL",
                icao: "KPHL",
                region: .northAmerica,
                latitude: 39.8719,
                longitude: -75.2411,
                runwayLength: 3200,
                elevation: 11,
                demand: AirportDemand(passengerDemand: 8.8, cargoDemand: 8.2, businessTravelRatio: 0.72, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 175000, cargoCapacity: 3600, gatesAvailable: 95, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Minneapolis-St. Paul International Airport",
                city: "Minneapolis",
                country: "United States",
                iata: "MSP",
                icao: "KMSP",
                region: .northAmerica,
                latitude: 44.8820,
                longitude: -93.2218,
                runwayLength: 3355,
                elevation: 256,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.5, businessTravelRatio: 0.70, tourismBoost: 0.75),
                facilities: AirportFacilities(terminalCapacity: 185000, cargoCapacity: 3800, gatesAvailable: 110, slotEfficiency: 0.91)
            ),
            Airport(
                name: "Detroit Metropolitan Airport",
                city: "Detroit",
                country: "United States",
                iata: "DTW",
                icao: "KDTW",
                region: .northAmerica,
                latitude: 42.2124,
                longitude: -83.3534,
                runwayLength: 3658,
                elevation: 197,
                demand: AirportDemand(passengerDemand: 8.5, cargoDemand: 8.0, businessTravelRatio: 0.68, tourismBoost: 0.70),
                facilities: AirportFacilities(terminalCapacity: 170000, cargoCapacity: 3500, gatesAvailable: 105, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Charlotte Douglas International Airport",
                city: "Charlotte",
                country: "United States",
                iata: "CLT",
                icao: "KCLT",
                region: .northAmerica,
                latitude: 35.2140,
                longitude: -80.9431,
                runwayLength: 3048,
                elevation: 228,
                demand: AirportDemand(passengerDemand: 9.0, cargoDemand: 8.2, businessTravelRatio: 0.72, tourismBoost: 0.72),
                facilities: AirportFacilities(terminalCapacity: 185000, cargoCapacity: 3600, gatesAvailable: 115, slotEfficiency: 0.90)
            ),
            Airport(
                name: "Salt Lake City International Airport",
                city: "Salt Lake City",
                country: "United States",
                iata: "SLC",
                icao: "KSLC",
                region: .northAmerica,
                latitude: 40.7899,
                longitude: -111.9791,
                runwayLength: 3659,
                elevation: 1288,
                demand: AirportDemand(passengerDemand: 8.2, cargoDemand: 7.5, businessTravelRatio: 0.65, tourismBoost: 0.80),
                facilities: AirportFacilities(terminalCapacity: 160000, cargoCapacity: 3200, gatesAvailable: 88, slotEfficiency: 0.89)
            ),
            Airport(
                name: "Portland International Airport",
                city: "Portland",
                country: "United States",
                iata: "PDX",
                icao: "KPDX",
                region: .northAmerica,
                latitude: 45.5887,
                longitude: -122.5975,
                runwayLength: 3353,
                elevation: 9,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 7.2, businessTravelRatio: 0.65, tourismBoost: 0.82),
                facilities: AirportFacilities(terminalCapacity: 150000, cargoCapacity: 3000, gatesAvailable: 78, slotEfficiency: 0.88)
            ),
            Airport(
                name: "Austin-Bergstrom International Airport",
                city: "Austin",
                country: "United States",
                iata: "AUS",
                icao: "KAUS",
                region: .northAmerica,
                latitude: 30.1945,
                longitude: -97.6699,
                runwayLength: 3658,
                elevation: 165,
                demand: AirportDemand(passengerDemand: 7.8, cargoDemand: 6.8, businessTravelRatio: 0.68, tourismBoost: 0.78),
                facilities: AirportFacilities(terminalCapacity: 150000, cargoCapacity: 2800, gatesAvailable: 72, slotEfficiency: 0.87)
            ),
            Airport(
                name: "Nashville International Airport",
                city: "Nashville",
                country: "United States",
                iata: "BNA",
                icao: "KBNA",
                region: .northAmerica,
                latitude: 36.1245,
                longitude: -86.6782,
                runwayLength: 3353,
                elevation: 183,
                demand: AirportDemand(passengerDemand: 7.5, cargoDemand: 6.5, businessTravelRatio: 0.58, tourismBoost: 0.85),
                facilities: AirportFacilities(terminalCapacity: 145000, cargoCapacity: 2600, gatesAvailable: 68, slotEfficiency: 0.86)
            ),
            // INDIA (add to Asia section)
            Airport(
                name: "Surat International Airport",
                city: "Surat",
                country: "India",
                iata: "STV",
                icao: "VASU",
                region: .asia,
                latitude: 21.1141,
                longitude: 72.7419,
                runwayLength: 2680,
                elevation: 16,
                demand: AirportDemand(passengerDemand: 6.5, cargoDemand: 6.8, businessTravelRatio: 0.72, tourismBoost: 0.55),
                facilities: AirportFacilities(terminalCapacity: 105000, cargoCapacity: 2300, gatesAvailable: 48, slotEfficiency: 0.82)
            ),
            Airport(
                name: "Pune Airport",
                city: "Pune",
                country: "India",
                iata: "PNQ",
                icao: "VAPO",
                region: .asia,
                latitude: 18.5821,
                longitude: 73.9197,
                runwayLength: 2530,
                elevation: 591,
                demand: AirportDemand(passengerDemand: 7.2, cargoDemand: 6.5, businessTravelRatio: 0.70, tourismBoost: 0.60),
                facilities: AirportFacilities(terminalCapacity: 120000, cargoCapacity: 2200, gatesAvailable: 52, slotEfficiency: 0.84)
            )
        ]
    }
    
    // Helper functions
    func airport(byCode code: String) -> Airport? {
        allAirports.first { $0.iata == code || $0.icao == code }
    }
    
    func airports(byRegion region: Region) -> [Airport] {
        allAirports.filter { $0.region == region }
    }
    
    func airports(byCountry country: String) -> [Airport] {
        allAirports.filter { $0.country == country }
    }
    
    func majorHubs() -> [Airport] {
        allAirports.filter { $0.demand.passengerDemand >= 9.0 }
    }
    
    func calculateDistance(from: Airport, to: Airport) -> Int {
        // Haversine formula for great circle distance
        let earthRadius = 6371.0 // km
        let lat1 = from.latitude * .pi / 180
        let lat2 = to.latitude * .pi / 180
        let dLat = (to.latitude - from.latitude) * .pi / 180
        let dLon = (to.longitude - from.longitude) * .pi / 180
        
        let a = sin(dLat/2) * sin(dLat/2) +
        cos(lat1) * cos(lat2) *
        sin(dLon/2) * sin(dLon/2)
        let c = 2 * atan2(sqrt(a), sqrt(1-a))
        
        return Int(earthRadius * c)
    }
}
